### ISSUE TITLE
Templating init failed in Grafana

### ISSUE THREAD

**Issue by aravind-nallan** [nosqlbench/nosqlbench#101]
While launching grafana in the browser I see the dashboard but no data because of this error.
![Screen Shot 2020-03-25 at 8 35 49 PM](https://user-images.githubusercontent.com/14622838/77665808-265d4380-6f4e-11ea-9093-12f987742f3a.png)

**Comment by phact** [comment]
@aravind-nallan can you reproduce this?

**Comment by jshook** [comment]
@aravind-nallan Any news on this? Is it still an issue?

**Comment by aravind-nallan** [comment]
Sorry completely busy with search perf testing at Venmo. I’ll try again today and let you know.

**Comment by david-joy-ds** [comment]
@jshook @phact I have the same error happening. However, I can see graphs in promethus.

**Comment by david-joy-ds** [comment]
@phact and I were able to look at the issue and fix it. We were able to fix it by going into the grafana data source location and by adding the ip address of the Prometheus host in the URL.

**Comment by BrandonBordeaux** [comment]
I ran into this issue today as well when accessing Grafana from a remote client.

@jshook - What are your thoughts on updating the Prometheus data source URL to use the Docker host IP instead of localhost?

**Comment by jshook** [comment]
I believe this was fixed by a contribution from @weideng1 , so I'm closing this issue. If it comes up again, please let us know!
