### ISSUE TITLE
Provide a nice way to update the dashboard to a newer version

### ISSUE THREAD

**Issue by phact** [nosqlbench/nosqlbench#103]
Include stale dashboard detection.

This might require storing a dashboard version hash in .nosqlbench to see if the current dashboard is outdated. It would also have to support non default grafana creds (perhaps prompt the user, don't store creds anywhere).

**Comment by jshook** [comment]
With the metrics dashboard being externalized, this may no longer apply. There are ways to manage this more directly now with the current grafana features. We'll re-approach this again if needed.
