### ISSUE TITLE
cfg data API does not match primitive types for type inference correctly

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1074]
When using the cfg APIs for activity params, you should be able to use 
Param.default("name",1234) for the model, and then get a result which is a primitive int.
This may be broken but undetected due to special case not being used by many users.
(The special case being changing the default port, for example)

This code should work as describe above.

**Comment by msmygit** [comment]
```
CoreMotor    Error in core motor loop:java.lang.RuntimeException: while binding request in cycle 0: config parameter 'name' is not assignable to required type 'class java.lang.Integer'
java.lang.RuntimeException: while binding request in cycle 0: config parameter 'name' is not assignable to required type 'class java.lang.Integer'
```
is the error that we receive in the above case.

**Comment by jshook** [comment]
For now, the work-around would be to use a boxed type as your declared type in the calling code. So above, you would assign `Integer port=` instead of `int port=`. This is not ideal, but it will allow these cases to work for now. When the type verification is improved, we can replace these call sites with the primitive version.

**Comment by jshook** [comment]
@msmygit I've realized this was a bug in the code. 'name' is indeed not intended to be assignable to Integer, and unit tests I've added confirm expected API behavior.
