### ISSUE TITLE
Provide a way to access values from property files.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1076]
There should be a distinct way to access named properties from specific property files. 

This should work much like environment variable access, with similar but distinct syntax.

- Users may want to provide property files which set global System properties for later reference.
- Users may want to provide a property file specifically within a var reference, or a symbolic property file via another variable.

**Comment by dave2wave** [comment]
It looks like the NBEnvironment class has the capability to take a property map in the interpolate call. It would be interesting to add a property file reference to NBAtFile or add a property file reference that is similar to AtFiles.

**Comment by dave2wave** [comment]
Possible implementation would be to add a global option to NBCLIOptions which processes a property file into the NBEnvironment singleton.

**Comment by dave2wave** [comment]
Do this through AtFile mechanism via suffix matching

**Comment by dave2wave** [comment]
I have code to use properties files as AtFiles and just need to add tests.

As far as using properties files as environment variables the best approach is to use a global cli option to add properties through NBEnviroment.

**Comment by dave2wave** [comment]
I'm going to expand the scope of this issue to support the inclusion of property files in the workload yaml.
