### ISSUE TITLE
reinit docker after partial removal fails with error

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#108]
When you remove your docker container images without also removing the docker dashboard state in `~/.nosqlbench/...`, the next time you use --docker-metrics, you get an error.

**To Reproduce**
1. `nb .... --docker-metrics`
2. `docker stop grafana prom graphite-exporter`
3. `docker rm grafana prom graphite-exporter`
4. `nb .... --docker-metrics`

**What was Expected**
Normal init of docker metrics.

**Comment by jshook** [comment]
@phact Does the current behavior address the issue above?

**Comment by phact** [comment]
Pretty sure yes

**Comment by jshook** [comment]
closing this issue after the last round of robustness fixes
