### ISSUE TITLE
Include test coverage of workload listing (yaml verifications)

### ISSUE THREAD

**Issue by jeffbanks** [nosqlbench/nosqlbench#1107]
**What is the ideal scenario for using this feature?**
Produce an error or success for running a --list-workload using nb binary

**Is your feature request related to a problem? Please describe.**
Yes, we have formatting and changes to .yaml files that can impact runtime usage.

**Comment by dave2wave** [comment]
Related to #1919

**Comment by dave2wave** [comment]
There is an integration test here: `./nbr/src/test/java/io/nosqlbench/engine/core/script/NBCliIntegrationTests.java`
