### ISSUE TITLE
It would be great if all the documentation was on a single page.

### ISSUE THREAD

**Issue by BrynCooke** [nosqlbench/nosqlbench#116]
**What is the ideal scenario for using this feature?**
New users trying to find information in the documentation.

**Is your feature request related to a problem? Please describe.**
Currently it is difficult to search the docs as information is hidden when selecting different subheadings. If the documentation was a single page users could use the find functionality in their browser to locate information that is relevant. For a project of this size this is preferable dedicated search functionality.

**Comment by jshook** [comment]
There are simply too many docs to put in one page. We're working on improving the docs to be searchable, though. If we had a search system that was responsive and inclusive of all the content in the docs, do you think this would have helped you?

**Comment by jshook** [comment]
Search in docs has been added since this was filed.
