### ISSUE TITLE
com.datastax.oss.driver.api.core.connection.ConnectionInitException

### ISSUE THREAD

**Issue by ITLULU** [nosqlbench/nosqlbench#1169]
when I use jdk17 compile and test, it will report this error.  I don't know how to solve this problem. do you have meet this issue.

I have see ChannelHadlerRequest's method names writeListener it will timeout.

  private void writeListener(Future<? super Void> writeFuture) {
    if (writeFuture.isSuccess()) {
      timeoutFuture =
          channel.eventLoop().schedule(this::onTimeout, timeoutMillis, TimeUnit.MILLISECONDS);
    } else {
      String message =
          String.format("%s: failed to send request (%s)", describe(), writeFuture.cause());
      fail(message, writeFuture.cause());
    }
  }

**Comment by jshook** [comment]
insufficient detail
