### ISSUE TITLE
Warn user when template parameters overlap driver parameters

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#117]
When a user specifies an option like `compression` for a templatized parameter in yaml, but this parameter is also a valid driver option (as it is for the cql driver), then users should be warned that this is likely to generate errors.

In such cases, it is almost certain that the parameters are not intended to be used in both places in exactly the same way, even just for formatting reasons.

**Comment by dave2wave** [comment]
So the issue is identifying possible errors like:

1. `grpc_port=TEMPLATE(grpc_port,6334)`
2. `token_file=TEMPLATE(token_file)`

**Comment by dave2wave** [comment]
Probably the Advisor check needs to be in both `StrInterpolator` and `NBCLIScenarioPreprocessor`.

**Comment by dave2wave** [comment]
Duplicates #1003

**Comment by dave2wave** [comment]
Basically we need to test the hierarchy of parameters names and not conflicts that alter or otherwise have inconsistent values.
