### ISSUE TITLE
Configuration Layering should be implemented in a uniform way

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1187]
There is a better way to attack this. We should have a singular capability which allows us to reference external values, whether they be from the environment, other files, or whatever.
For example, a format like `{resolver:name}` can make it very clear what the resolver is. You could access an environment variable like `{ENV:HOME}`, or the contents of a file as `{FILE:myfile}`. As long as the beginning contains the resolver name, then it is uniformly parsable.

By having a singular syntactical form we can properly parse it and thus introduce the ability to layer or indirect where users may want this. It also allows us to extend the value resolver mechanism in a consistent way where each one is documented. The precedence can be established, and potentially overridden by the user.

(was) All key configuration mechanisms should work harmoniously in any layering arrangement, and there should be unit and integration tests for all of the common cases.

**Comment by dave2wave** [comment]
For NBIO we have a resolver chain to sort the order for finding files in a stack of FILE, CLASSPATH, CACHE, and URL.

What does the Parameter resolution stack look like:
1. Environment variables.
2. CMD Params argvs including Atfiles.
3. Workload Params.
4. Driver Adapter and scenarios.
We resolve from inner to outer and the convention for TEMPLATEs is to take care to avoid parameter name collisions. The resolution of names and values does not go through a cohesive code path.
Without a clear plan for parameter resolution that exists in a singular place this issue cannot be implemented.

**Comment by dave2wave** [comment]
The current layers look like:
1. Activity / CMD Parameters / Scenarios
2. TEMPLATE Parameters (which may or could pull in ENV variables)
3. YAML - Doc, Block, Ops

**Comment by dave2wave** [comment]
There are two places that this could be applied.

1. When parsing cli parameters in ActivityDef. In this case the resolver form can make sense.
2. When parsing TEMPLATE formats in StrInterpolator. In this case the resolver format conflicts with the option to use this resolver format.

I suggest that the resolver be limited to command line parsing to expand or otherwise fill in values and in this case we should consider using the usual format for ENV and AtFiles for FILE.

**Comment by dave2wave** [comment]
I'm closing this as it is contrary to current similar initiatives and it's unclear how this yet another way is an advantage
