### ISSUE TITLE
Indentation Errors on Auto-Generated Binding Functions

### ISSUE THREAD

**Issue by MikeYaacoubStax** [nosqlbench/nosqlbench#1197]
**Description**
Some auto-generated binding functions have unnessary nested indentations, these indentations are causing some pages to load slowly, and some like 'funcref_collections' to not load at all.

**To Reproduce**
go to: [funcref-collections](https://docs.nosqlbench.io/reference/bindings/funcref-collections/)

**What was Expected**
A well indented page that does not hang on any browser

**Additional context**
Upon investigation: this has to do with some patterns of code used in the automatically generated markdown that indicate an indentation to zola (some combinations of '>' with other characters)

**Screenshots*
![image](https://user-images.githubusercontent.com/117678633/229537318-3ef91a62-370c-4124-8191-900d1836220f.png)

**Comment by jeffbanks** [comment]
Resolved in PR #1198
