### ISSUE TITLE
Implement NBAdvisor layer for all detectable issues which may cause unexpected behavior.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#12]
Assertive mode is a feedback setting which will tell novice users when something doesn't look right for a user-interactive scenario.

Examples:

There are zero cycles in an activity
There are zero activites in a scenario
a parameter isn't being used
In some cases, especially with automated testing calling into eb, it is valid for these conditions to occur. For those cases, it would be nice to be able to say assertive=false to delegate trust to the caller for configuration sanity.

Originally filed as https://github.com/engineblock/engineblock/issues/184

The steps to implement this are:
- [ ] Add enum for the different validation levels.
- [ ] Document validation level semantics.
- [ ] Enable validation for unused parameters
- [ ] Enable validation for client resource overloads.

After reviewing other issues related to this, it seems that there are some distinct level of feedback that are appropriate:
1. ignore - This means provide no user feedback and allow all settings to be applied as given if possible.
2. advise - Inform the user of cases which appear to be problematic or which could cause unexepected behavior.
3. dryrun - Exercise the advisory logic, but use dryrun semantics where all advise is accumulated into a single output that the user can cross-check things with.
4. enforce - Throw an error in any case which advise would normally alert the user.

Essentially in every case where advise would cause user feedback, enforce should throw an error. In both cases, they same advisory text should be given about the potential bad effects. And if possible, example syntax for an alternate way of addressing the issue should be provided. Ideally, such example syntax is usable copypasta for the current scenario.

For implementing this, a new type called NBAdvisor should be created which enforces a few contractual requirement for developers. Specifically developers should be required to construct valid advisor objects which:
1. Knows its usage context and how to log or reference docs using some distinct and stable name.
2. Has a uniform output which can be marshalled into some advisor specific view, such as with a dry-run test output.
3. Provides details which clearly explain why the advise is being given.
4. If possible provide an example of a copypasta which can be used to fix the user's current configuration.

**Comment by dave2wave** [comment]
1. Enum
2. CLI global options
3. Factory under NBComponentCreate
4. ExceptionType for exception handling

**Comment by dave2wave** [comment]
We should explore an alternative to an enum. Instead there are two global options.
1. `--advisor` which causes Advisors to be created on components which will analyze and provide advice.
2. `--enforcer` which causes Advisors to enforce correctness.
If you have both set then you will get advice in addition to correctness. If you just give `--enforcer` then you will be aborted, but without much analysis.
