### ISSUE TITLE
Make sure we trim tags from cli

### ISSUE THREAD

**Issue by phact** [nosqlbench/nosqlbench#120]
**Describe the bug**
Make sure we trim tags from cli

**To Reproduce**
./nb run type="cql" alias="ebdse_mostly_writes" yaml="https://gist.githubusercontent.com/.../simple_compaction_schema_v2.yaml" cl="LOCAL_ONE" showcql="false" interval="1" tags="phase: main" cycles="0..20000000" threads="100" host="10.101.33.145" maxtries="10" cbopts=".withSocketOptions(new SocketOptions().setReadTimeoutMillis(20000)) .withPoolingOptions(new PoolingOptions().setConnectionsPerHost(HostDistance.REMOTE, 16, 64))" errors="histogram" keyspace="density" key-count="100000000" ckey-count="100000" blob-len="19040" --log-histograms '/home/automaton/fallout_artifacts/ebdse_mostly_writes.hdr::5m' --log-histostats '/home/automaton/fallout_artifacts/ebdse_mostly_writes.csv::5m' --report-graphite-to 10.101.36.97:2003 --metrics-prefix client_node0 2>&1 | tee /home/automaton/fallout_artifacts/ebdse_mostly_writes.log

note the space `tags="phase: main" `

errors with `There were no unfiltered statements found for this activity.`

**Comment by jshook** [comment]
Fixed in master
