### ISSUE TITLE
Encapsulate instrumentation libraries into nb-metrics module

### ISSUE THREAD

**Issue by jeffbanks** [nosqlbench/nosqlbench#1219]
Metrics and instrumentation concerns should be carved out and migrated to a new module called *nb-metrics*.
This is necessary to facilitate the creation of a clean boundary around metrics requirements, expressed in contract/interface form.

When doing this, lots of dependency challenges are likely to arise, but that is part and parcel of the disentangling that is needed.

**Comment by jshook** [comment]
With the augmentations we've made on top of the base layer of metrics, we can now move forward without a contract layer. Although this would still be nice, it is no longer essential.
