### ISSUE TITLE
grafana authentication failed after removing containers 

### ISSUE THREAD

**Issue by david-joy-ds** [nosqlbench/nosqlbench#122]
`Unable to configure dashboard, grafana authentication failed` after removing the previous ages from docker and trying again. While I did change the admin password in web url when login to graphana. 

1. nb .... --docker-metrics
2. docker stop grafana prom graphite-exporter
3. docker rm grafana prom graphite-exporter
4. nb .... --docker-metrics

Expected : 
Should start normally and run the test.

**Comment by david-joy-ds** [comment]
Fixed : After removing ./nosqlbench folder. 
When I tried to restart the next test, this error was gone.

**Comment by phact** [comment]
I think@weideng1 and I fixed this one last week.
