### ISSUE TITLE
Packaged nb binary gives libfuse.so.2 error on CentOS 7.6

### ISSUE THREAD

**Issue by jblang** [nosqlbench/nosqlbench#123]
**Describe the bug**
The packaged nb binary won't run on CentOS 7.6 due to missing libfuse.so.2, even after installing fuse.

This was using release 3.12.88 of nosqlbench

**To Reproduce**
1. Fresh install of CentOS 7.6 and download nb 3.12.88 
2. Run nb and see libfuse.so.2 error
3. Optionally install fuse package and see the same error when rerunning nb.

**Screenshots, if applicable**

```
Installed:
  fuse.x86_64 0:2.9.2-11.el7
Complete!
[automaton@ip-10-101-35-176 ~]$ ./nb
dlopen(): error loading libfuse.so.2
AppImages require FUSE to run.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
```

**Comment by dave2wave** [comment]
We will need to provide a troubleshooting comment in the build scripts.

**Comment by dave2wave** [comment]
The build scripts contain a comment to troubleshooting information.
