### ISSUE TITLE
Paging seems broken in nosqlbench5

### ISSUE THREAD

**Issue by anderoo** [nosqlbench/nosqlbench#1231]
**Describe the bug**

Paging doesn't seem to work with cql and nosqlbench5, regardless of how high the maxpages
value is, I keep running into the same error.

**To Reproduce**

Spin up a cluster with the following benchmark yaml, trigger the schema, 
rampup and eventually main-read.

```
description: |
  TODO

bindings:
  id: Shuffle(0,10); Template("{}-{}", Hash(), Hash());
  date: Shuffle(0,31); ToString();
  timestamp: AddHashRange(0L,2592000L); Mul(1000); StartingEpochMillis("2023-04-01 12:00:00"); ToJavaInstant();
  value: Shuffle(0,50); Template("value-{}-{}-{}", Hash(), Hash(), Hash());

blocks:
  schema:
    params:
      prepared: false
    ops:
      create-keyspace: |
        CREATE KEYSPACE IF NOT EXISTS TEMPLATE(keyspace, baselines)
        WITH replication = {'class': 'NetworkTopologyStrategy', 'ue1': 'TEMPLATE(rf,3)'}
        AND durable_writes = true;
      create-table : |
        CREATE TABLE IF NOT EXISTS TEMPLATE(keyspace,baselines).TEMPLATE(table,test) (
          id text,
          date text,
          timestamp timestamp,
          value text,
          PRIMARY KEY((id), date, timestamp)
        ) WITH CLUSTERING ORDER BY (date DESC, timestamp DESC)
        AND compaction = { 'class':'LeveledCompactionStrategy' }
        AND compression = { 'class': 'LZ4Compressor', 'chunk_length_in_kb': 4 };
  rampup:
    params:
      cl: TEMPLATE(write_cl,LOCAL_ONE)
      prepared: true
      page_size: 100
      maxpages: 100
    ops: |
      INSERT INTO TEMPLATE(keyspace,baselines).TEMPLATE(table,test) (id, date, timestamp, value)
      VALUES ({id}, {date}, {timestamp}, {value})
  main-read:
    params:
      cl: TEMPLATE(read_cl, LOCAL_ONE)
      prepared: true
    statements:
      select:
        op: |
          SELECT * FROM baselines.test
          WHERE id={id}
          ORDER BY date DESC, timestamp DESC
```

Schema: `./nb5 run workload=bench-small.yaml host={HOST} driver=cql localdc=ue1 tags=block:schema`

Rampup: `./nb5 run workload=bench-small.yaml host={HOST} driver=cql localdc=ue1 cycles=10000 striderate=100 stride=100 tags=block:rampup threads=10`

Read: `./nb5 run workload=bench-small.yaml host={HOST} driver=cql localdc=ue1 cycles=1 striderate=100 stride=100 tags=block:main-read threads=180`

This runs into the following error, regardless of how high we bump maxpages:

```
Error in core motor loop:java.lang.RuntimeException: io.nosqlbench.adapter.cqld4.exceptions.UnexpectedPagingException: Additional paging would be required to read the results from this query fully, but the user has not explicitly indicated that paging was expected. fetched/allowed: 102/100 fetchSize(100): SELECT * FROM baselines.test
```

**What was Expected**

The maximum page rows per partition should be ~1000, so we should be able to page through this
with the given maxpages and page_size.

**Additional context**
OS: Windows, Linux (distribution), macOS ...
environment: k8s, docker, ...
version info (`./nb --version` or `java -jar nb.jar --version`)

**Screenshots, if applicable**

**Comment by jeffbanks** [comment]
Hi @anderoo, thanks for reporting this issue.

Can you provide the specific version of `nb5` as well as the `trace` output of your `read` command?  Also, any details of the environment you are running this scenario on.  

For example, run your `block:main-read` with `-vvv > trace.out` included and capture the output of that run.

I was able to run your scenario locally without that error, and want to align what else may be the issue on your end.  

Thank you!

**Comment by jshook** [comment]
@anderoo I was able to find the issue with this. I'll have a fix in before the next release is out.
