### ISSUE TITLE
Support SQL workloads using JDBC driver?

### ISSUE THREAD

**Issue by weideng1** [nosqlbench/nosqlbench#124]
I know it is a bit funny to use nosqlbench to stress test SQL databases, but I don't see any reason why not. After all, nosqlbench has the best data generation utilities built-in (much better than faker), among many other benefits like scripting support, so IMHO it could be very helpful to leverage it for some SQL benchmarks or stress tests. Also, nosql can also be interpreted as "not-only SQL".

**Comment by Pierrotws** [comment]
Actually I had the same idea, but for a pure Nosql usage : phoenix database use a JDBC driver

**Comment by jshook** [comment]
This has been supported for some time. We've even used it to test vector variants.
