### ISSUE TITLE
Option for setting SSL Validation False Flag

### ISSUE THREAD

**Issue by ksmaung** [nosqlbench/nosqlbench#1260]
**What is the ideal scenario for using this feature?**
Performance testing for non-prod data

**Is your feature request related to a problem? Please describe.**
For Cassandra deployment with 40+ clusters with self-signed certificates, it would be impractical, if not impossible, to create trust store certificates for each node for establishing connections to run NoSqlBench.  This option is already provided by the Cassandra Java driver.
Propose to add “sslvalidation=false” to bypass SSL validation to relieve the burden of creating trust store certificate for every node. 

**Would you like to help implementing or testing it?**
We would be happy to implement it if there’s no takers as it is needed sooner.

**Additional context**
Current supported options for SSL
nb help SSL

help ssl
# SSL
 
Supported options:
 
- **ssl** - specifies the type of the SSL implementation.
    Disabled by default, possible values are `jdk`, and `openssl`.
 
- **tlsversion** - specify the TLS version to use for SSL.
 
    Examples:
    - `tlsversion=TLSv1.2` (the default)
 
For `jdk` type, the following options are available:
 
- **truststore** - specify the path to the SSL truststore.
 
    Examples:
    - `truststore=file.truststore`
 
- **tspass** - specify the password for the SSL truststore.
 
    Examples:
    - `tspass=truststore_pass`
 
- **keystore** - specify the path to the SSL keystore.
 
    Examples:
    - `keystore=file.keystore`
 
- **kspass** - specify the password for the SSL keystore.
 
    Examples:
    - `kspass=keystore_pass`
 
- **keyPassword** - specify the password for the key.
 
    Examples:
    - `keyPassword=password`
 
 
For `openssl` type, the following options are available:
 
- **caCertFilePath** - path to the X509 CA certificate file.
 
    Examples:
    - `caCertFilePath=cacert.crt`
 
- **certFilePath** - path to the X509 certificate file.
 
    Examples:
    - `certFilePath=ca.pem`
 
- **keyFilePath** - path to the OpenSSL key file.
 
    Examples:
    - `keyFilePath=file.key`

**Comment by jeffbanks** [comment]
Hi @ksmaung, after looking at this in more detail, can you provide some more information about how you want to bypass the validation in our current set of supported options for `jdk` and `openssl` as they apply to keystore and truststore settings?  

When applying the `sslvalidation=false`, are you expecting that any `truststore` settings would be completely ignored, but the `keystore` settings would still be verified?

**Example**
```
  "ssl=openssl",
  "sslValidation=false",  
  "certFilePath=src/test/resources/ssl/client_cert.pem",
  "keyFilePath=src/test/resources/ssl/client.key",
  "truststore=src/test/resources/ssl/non_existing.p12",
  "tspass=nosqlbench_server",  
  "keystore=src/test/resources/ssl/client.p12",
  "kspass=nosqlbench_client"
```

And in this case, what would be the expected level of validation?
```
"sslValidation=false",  
"ssl=openssl",
"caCertFilePath=src/test/resources/ssl/cacert.crt",
"certFilePath=src/test/resources/ssl/client_cert.pem",
"keyFilePath=src/test/resources/ssl/client.key"
```
Since we have many combinations for the security configuration in NB5, we want to ensure that we address how this would impact the other options.

**Comment by bschoening** [comment]
@jeffbanks disable SSL hostname validation happens on the client side, it allows a client (nosqlbench) to connect to a database node with a SSL certificate without validating the hostname against a Certificate Authority.  The most common situation is in dev and uat environments when the server has a self-signed certificate.

A common example in Java is with HttpClient where you can set the [NoopHostnameVerifier:](https://www.javadoc.io/doc/org.apache.httpcomponents/httpclient/4.5.3/org/apache/http/conn/ssl/NoopHostnameVerifier.html)
    var httpClient = HttpClients
        .custom()
        .setSSLContext(new SSLContextBuilder().loadTrustMaterial(null, TrustAllStrategy.INSTANCE).build())
        .setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE)
        .build();

**Comment by jeffbanks** [comment]
Thanks @bschoening for the additional information regarding the hostname validation!  

@ksmaung can you confirm what adapter you are using for your testing?   

I see where this is currently applied in NB5 with the `adapter-jdbc` using an `sslmode` option.  The default is `prefer` and allows for: disable , allow , prefer , require , verify-ca and verify-full.

`adapter-cqld4` or `adapter-jdbc`?

**Comment by ksmaung** [comment]
adapter-jdbc

**Comment by ksmaung** [comment]
@jeffbanks 
 adapter-cqld4 is the DataStax v4 driver and well-suited to work with Cassandra DB.
Thanks.

**Comment by jeffbanks** [comment]
SSL validation bypass option added in [PR#1289](https://github.com/nosqlbench/nosqlbench/pull/1289).
