### ISSUE TITLE
Failing to pull Docker image due to incompatible mediaType in manifest for nosqlbench/nosqlbench:5.17.2 using docker version 19.03.1

### ISSUE THREAD

**Issue by ksmaung** [nosqlbench/nosqlbench#1305]
**What is the ideal scenario for using this feature?**
Pulling nosqlbench/nosqlbench docker image from both external and internal repo

**Is your feature request related to a problem? Please describe.**
Fail to pull nosqlbench docker image from internal repository using the following command when building docker image
$ docker build --tag nosqlbench .
Sending build context to Docker daemon  2.048kB
Step 1/1 : from [containerregistry-xxx.company.net/container-external/docker.io/nosqlbench/nosqlbench:5.17.2](http://containerregistry-na.jpmchase.net/container-external/docker.io/nosqlbench/nosqlbench:5.17.2)
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

**Would you like to help implementing or testing it?**
No permission to push the image to Docker Hub

https://github.com/nosqlbench/nosqlbench/blob/main/.github/workflows/release.yml#L77 
uses: [docker/build-push-action@v3.3.0](https://github.com/nosqlbench/nosqlbench/issues/docker/build-push-action@v3.3.0) 

Need to upgrade to uses: docker/build-push-action@v4

"You can rebuild the image by updating the FROM statement in your Dockerfile. If your image manifest is out-of-date, there is a chance the image pulled from your FROM statement in your Dockerfile is also out-of-date. See the [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#from) and the [Dockerfile best practices guide](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) for more information on how to update the FROM statement in your Dockerfile "

**Additional context**
For Cassandra docker image the following command works but fails for nosqlbench 
% docker manifest inspect cassandra                   
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2212,
         "digest": "sha256:7da9eef9e4fe3aa1178efee2e14b09cea2ca93703743ae3b68d210364fa53651",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2212,
         "digest": "sha256:187c63527e3743ee8b321222b736b669af016d0d78cccf842a707a5186121041",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2212,
         "digest": "sha256:1416e52e1752dd76895c892aa4b378101195fd4b9e76ae1572a7ef1fe8454d2a",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2212,
         "digest": "sha256:47694e1e5c3aee5e532194741121000762eff2f32209620b8890b2a0899cb3e9",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2212,
         "digest": "sha256:29cc89efbc78674ac91808e7cf8715d39a7bbee85f5d6209670dbe393aaa4fc2",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
% docker manifest inspect nosqlbench:5.17.2
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

**Comment by bschoening** [comment]
Created PR https://github.com/nosqlbench/nosqlbench/pull/1504
