### ISSUE TITLE
Add support for `cyclerate_per_thread` in NB5

### ISSUE THREAD

**Issue by MMirelli** [nosqlbench/nosqlbench#1323]
**Describe the bug**
NoSQLBench 5 does not support `cyclerate_per_thread`. I would need that feature to do Pulsar load testing.

In other words, NB4, given a command containing `cyclerate_per_thread`, would spread the load across the number of threads, whereas NB5 is not.

**To Reproduce**
1. start pulsar standalone
2. `java -cp lib/*:nb.jar -v  --report-interval 10 run driver=pulsar config=pulsar-config.properties web_url=http://localhost:8080 service_url=pulsar://localhost:6650 cycles=0..2147483647 stride=50 workload=pulsar-producer-workload.yaml alias=producer-workload cyclerate=50,1.0 cyclerate_per_thread=true threads=10`
3. see input rate of 50 msg / s.

**What was Expected**
50 msg / s per thread, so 500 msg / s in total.

**Additional context**
OS: macOS 13.4
```
java -jar nb.jar --version
5.17.3-release
```

**Comment by jshook** [comment]
done in #1928
