### ISSUE TITLE
Allow for grafana API keys to be created from CLI

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1461]
When wiring NB to send labeled metrics with annotations to a grafana instance, auto-key is not possible as with a locally-managed instance via --docker-metrics. When sending annotations remotely, an admin needs to be able to configure an API key, either by providing it directly, or by asking nb to create one from admin login credentials in a secure way.

**Comment by dave2wave** [comment]
Why should NB be creating api tokens for a Grafana instance it is not managing?

**Comment by dave2wave** [comment]
Duplicate or very similar to #1467
