### ISSUE TITLE
Allow labels to be added to workloads natively

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1462]
For organizing and finding specific tests, we need to be able to the specific labels which identify them, both in workload templates, or on the command line, or both.

The metrics labeling system that is new to main should allow for arbitrary workload, activity, and/or op-level labels to be added. These labels should propagate to any downstream sources, like metrics collection, annotations, etc.

Since these need to be added at different levels, and we already have support for a hierarchic labeling system within NB, all we should have to do is add some additional ways of affixing labels at each level. This should also include adding global labels on the CLI or scenario level.

At different levels, the labels could be used for different things:

* Auxiliary op template labels can be used to make it easy to aggregate views of operations in dashboards. For example reads vs writes, vector ops vs non-vector ops, etc.
* Auxiliary activity labels can be used to distinguish between different phases or concurrent channels of a test across some useful logical boundary, such as consumer vs producer, etc. 
* Auxiliary scenario labels can be used to categorize and recall performance studies according to  testing parameters. For example, whether encryption or compression is enabled or not.

These labels are used in two places primarily, and should be documented as such:
* In metrics labels as sent to any downstream system which supports labeled metrics
* In annotation updates which are sent to grafana or any other downstream annotation collector

- [x] allow labels on the command line
- [x] allow labels on activities via activity params
- [x] allow labels for op templates

**Comment by dave2wave** [comment]
Are we searching for a general solution when a more specific one might make more sense? It seems that for this use case we want to enable adding a set of labels at the topmost level (and later in subtrees). Why not have a simple "test set" yaml and then intake that file at the start of a Session and then output those labels automatically?

**Comment by jshook** [comment]
> Why not have a simple "test set" yaml and then intake that file at the start of a Session and then output those labels automatically?
It's best if we can keep the workload descriptions contained to a single file as they are now. Even though users will sometimes accessorize with external files, the ability to hand some scenarios over to other engineers in a single file is quite valuable.

I have support for adding labels on the command line at the session level, to activities as activity parameters, and at the op template level in the workload. These will get pushed up to a PR soon.

**Comment by jshook** [comment]
This is supported at the op level as op fields, and at the activity level as an activity param.
The only layer missing now is in the workload spec in general. I'll make a separate issue for this.
