### ISSUE TITLE
annotations need matching instance identifier to mesh with metric labels

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1496]

**Comment by dave2wave** [comment]
AFACT the instance identifier is part of the prompush url.

**Comment by dave2wave** [comment]
Implement via label values like INSTANCE

**Comment by dave2wave** [comment]
One idea is to consider updating the prompush url according to the instance

**Comment by jshook** [comment]
For now, there is a more direct and pragmatic approach to making sure these are provided, although it doesn't deal with the DRY configuration principle yet.

https://github.com/nosqlbench/nosqlbench/issues/1500#issuecomment-1712958467
