### ISSUE TITLE
activity parameters should be more robust with upper/lower case

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#15]
Using the validation setting from #12 , there should be more robust ways of detecting upper/lower case mismatches.
For a relaxed mode, parameter names should match across upper and lower case, with a warning emitted.
For a stricter mode, parameter names must match case in order to be valid. An error should be thrown for case mismatches.

Before this can be worked, #12 must be complete.

**Comment by dave2wave** [comment]
There is quite a bit of confusion in the code around whether or not case matters for various parameters. EG. for some of the enums we have explicitly added `toLowerCase()`. Everyone of those would need to go through this case validation step.

**Comment by dave2wave** [comment]
How are these rules:
1. TEMPLATE parameters should be lowercase and with '_'
2. Mixed and upper case, and '-' are Advisor Warnings unless AdvisorLevel is enforce where they are Errors.

We have many example scenarios and templates where the name has a '-'. Fixing these is another issue ...

**Comment by dave2wave** [comment]
Make this part of #1609
