### ISSUE TITLE
named metrics timer operator for CQL statements

### ISSUE THREAD

**Issue by ShaunakDas88** [nosqlbench/nosqlbench#152]
we will need this for 6.8.1 certification, being able to use the substrides mechanism that has been used for previous CQL certifications.

**Comment by jshook** [comment]
This is addressed by https://github.com/nosqlbench/nosqlbench/commit/998439c8a19d92c2c30fdd0435dd0bd38cbe92b8 and active in the latest nb4 release candidate.
