### ISSUE TITLE
make the relevancy functions have set labels instead of passing in the name

### ISSUE THREAD

**Issue by dave2wave** [nosqlbench/nosqlbench#1527]
precision and the other relevancy functions have a name argument that should be converted to our constant value and the label is internal and non-user chosen.

**Comment by jshook** [comment]
This is partially done, although the gauge logic for lambda-based gauge registration needs to be reworked to use the built-in labeling on the gauge instance as well as the provided metric family name. Further, lambda-based gauge need to support an auxiliary label set directly. This simply means that these gauge should implement NBLabeledElement appropriately, chaining parent label context.

**Comment by dave2wave** [comment]
This is tied in with #1528 where the gauge needs to know the name.

**Comment by jshook** [comment]
done
