### ISSUE TITLE
Version number should be added to logs and possibly error messages

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#16]
When diagnosing an issue, it is sometimes difficult to verify whether an issue should have been fixed or not if the diagnostic output doesn't indicate the version. It would be much easier if all diagnostic logs had an version included, like this:

"diagnostic error line here .... (version 3.12.43)"

Steps to implement:
- [ ] Move version detection earlier in NBCLI
- [ ] Update NBCLIErrorHandler to add details when called

**Comment by dave2wave** [comment]
This looks very easy. Will pass the version [here](https://github.com/nosqlbench/nosqlbench/blob/main/nb-engine/nb-engine-cli/src/main/java/io/nosqlbench/engine/cli/NBCLI.java#L137)
