### ISSUE TITLE
ensure that final report on metrics is shown at end of session

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1611]
This was previously carried by a custom result type known as ExecutionMetricsResult, which was a specialization of ExecutionResult.

Now that ScenarioResult the primary result type from a scenario execution, this should probably be the basis for handing results back to the session layer or similar for reporting a scenario summary (which was where the list of metrics dumped to screen previously came from.)

Ideas from Discussion:
* There is no longer one definitive stopping point for all scenarios and activities at which time a singular report should be given.
* We do not want to maintain any _ghost_ copies of components or their decorating state, like metrics. Thus, any post-results should be buffered to an appropriate channel within the normative component life-cycle hooks.
* One implementation idea would be to provide an output buffer within the component tree, (the session by default), and any component that wants to send to such a thing would find the first one at it's or a parent's level and send via that found service directly.

**Comment by MarkWolters** [comment]
code complete and pull request created
