### ISSUE TITLE
CyclesSpec   This cycles interval means zero total:null..null

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#1618]
**Describe the bug**
When `cycles=UNDEF` is used in the named scenarios, we get this below warning,

```
WARN  [scenarios:001] CyclesSpec   This cycles interval means zero total:null..null
```

**To Reproduce**
`15.7.5` from `main` branch

**Comment by jshook** [comment]
I believe this is fixed in the current code, so I'll close this for now. We'll look again if it pops up.
