### ISSUE TITLE
Add Support for HTTP Headers

### ISSUE THREAD

**Issue by jamesc127** [nosqlbench/nosqlbench#164]
**What is the ideal scenario for using this feature?**
Using NoSqlBench for testing an Astra Database via the REST API requires HTTP headers for the auth token, among other things. 

**Is your feature request related to a problem? Please describe.**
No, just thinking of using this for my DA Astra demo.

**Would you like to help implementing or testing it?**
I think with headers available I could get the rest going.

**Additional context**
[This link here](https://astra.readme.io/docs/retrieving-rows-from-your-table) outlines the `GET` message format for Astra.

**Comment by jamesc127** [comment]
Per @phact, I believe the edit is here:

https://github.com/nosqlbench/nosqlbench/blob/main/driver-http/src/main/java/io/nosqlbench/activitytype/http/HttpAction.java#L88

**Comment by jshook** [comment]
I did a quick experiment to see if we could retrofit the HTTP driver to use a more modern configuration format. It looks like it is mostly done. This will make all requests fully customizable, including headers, content source etc.

Something usable should be in place by tomorrow.

**Comment by jshook** [comment]
This is implemented in the current version of the HTTP driver, and should be ready for alpha level testing. Additional features will be added to the HTTP driver before it is more widely announced:

* [ ] result verification parameters (status, content) and documentation
* [ ] possible request chaining for redirects, etc and documentation
* [ ] metrics and documentation
* [ ] exception handling design review and documentation

**Comment by jshook** [comment]
@jamesc127 This is supported in the current http refresh, but it hasn't been released as a fully tested and documented driver yet. Please let me know if you are interested in helping get it across the finish line with some testing and maybe some docs.

**Comment by jeromatron** [comment]
Hi @jamesc127 are you able to try with the latest version that includes fixes that @jshook and I worked on and Shook got into a release recently?  I was able to get the http driver working with Stargate's REST/Document API to load data so I don't see a reason why it wouldn't work with GET.  The version that works with it is https://github.com/nosqlbench/nosqlbench/releases/tag/nosqlbench-3.12.154 and later.  The http driver documentation has been [updated](http://docs.nosqlbench.io/#/docs/drivers/http.md) with new diag features and there are also additional features like URLEncode and URLDecode (in the [conversion bindings documentation](http://docs.nosqlbench.io/#/docs/bindings/funcref_conversion.md).  Other examples of running with it are in [this repo](https://github.com/jeromatron/shine/tree/main/nosqlbench) if that helps as well.

Ultimately, I'm wondering if this has been fixed.

**Comment by jshook** [comment]
Headers are supported in the documented format now.
