### ISSUE TITLE
DoubleHashedRange should be deprecated, not removed

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1669]
For some workloads, previous use of DoubleHashedRange was meant to be deprecated and updated to HashRange to be like all the others using standard naming. However it was removed, which creates an undue burden on users to update a trivial name before they can run their workload. it should be put back in as a wrapper around HashRange

**Comment by dave2wave** [comment]
I see `HashedDoubleRange` in the docs. I see that the `HashRange` class is defined here: `./nb-virtdata/virtdata-lib-basics/src/main/java/io/nosqlbench/virtdata/library/basics/shared/unary_int/HashRange.java`. What would be the minimum to put this back? Adding a class called DoubleHashedRange adjacent to HashRange? Anything else?

**Comment by jshook** [comment]
We've had no reports of this since it was filed. As long as users have already converted their workloads to use the more consistent naming, we should not add this back in at this time.
