### ISSUE TITLE
Allow parameters such as "async" to be explicitly unset

### ISSUE THREAD

**Issue by alicel** [nosqlbench/nosqlbench#167]
At the moment, the "async" parameter is considered unset when it is absent from the activity call. While this makes perfect sense in direct activity calls from the cli as well as simple scenario scripts, there can be cases where a scenario script needs to set a specific activity call to be synchronous or asynchronous programmatically. 

An example is a script that accepts an input parameter such as "runPerformancePhasesAsync", so that the user is able to decide whether they want some phases to be run asynchronously or not. To support this, it would be convenient if the scenario script could call the activity with the async parameter set to either a valid value or some unset special value - as opposed to having to exclude this parameter completely in the synchronous case, which means changing the structure of the JSON and can be awkward to implement.

**Comment by jshook** [comment]
This has been as a feature of the ScriptParams.withOverrides(...) which is available on the params object that is injected into every scripting environment.
