### ISSUE TITLE
Bug: ANTLR Runtime version 4.12.0 used for parser compilation does not match the current runtime version 4.11.1

### ISSUE THREAD

**Issue by pjta** [nosqlbench/nosqlbench#1671]
**Describe the bug**
I'm getting the above mentioned error when following "Getting Started/Running nb5" (see https://docs.nosqlbench.io/getting-started/00-get-nosqlbench/)

>  $ java -jar nb5.jar examples/bindings-basics
ANTLR Runtime version 4.12.0 used for parser compilation does not match the current runtime version 4.11.1
ANTLR Runtime version 4.12.0 used for parser compilation does not match the current runtime version 4.11.1
escaped : "quotes included!"
 lambda : pre-0-post
   name : zero
   show : {}
      n : 0
 typeof : java.lang.String

**What was Expected**
Expecting to  "run a built-in scenario located in the workload template named 'bindings-basics'. " as described in the doc.

**Additional context**
MacOs: Sonoma 14.0 (23A344)
>  $ java -jar nb5.jar --version
5.17.3-release
>  $ java --version
java 17.0.9 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)

**Comment by jshook** [comment]
The version for runtime, libs and plugin for Antlr in the 5.17 maintenance branch have been synchronized. Thanks!
