### ISSUE TITLE
Cant not find p99 latency in output

### ISSUE THREAD

**Issue by gaoshengL** [nosqlbench/nosqlbench#1778]
I execute cmd:
./nb5 cql-test default host=10.24.87.4 localdc=dc1 

P999&P99 lantency is import for me,but I cant not find p99 latency in output。And I found no parameter to display it.

use cql-test.yaml as fellow:
description: |
  A workload with only text keys and text values.
  This workload is rather simple but it is useful for demonstration purposes.
  If you want a more thorough example, you might be interested in the
  baselinesv2/cql-* workloads.
  defaults:
   TEMPLATE(keyspace,baselines)
   TEMPLATE(table,keyvalue)

scenarios:
  default:
    schema: run driver=cql tags==block:schema threads==1 cycles==UNDEF
    #rampup: run driver=cql tags==block:rampup cycles===TEMPLATE(rampup-cycles,10000000) threads=auto
    main-read: run driver=cql tags=='block:main-read' cycles===TEMPLATE(main-cycles,100) threads=40
  astra:
    schema: run driver=cql tags==block:schema-astra threads==1 cycles==UNDEF
    rampup: run driver=cql tags==block:rampup cycles===TEMPLATE(rampup-cycles,10000000) threads=auto
    main: run driver=cql tags=='block:main-.*' cycles===TEMPLATE(main-cycles,10000000) threads=auto
  basic_check:
    schema: run driver=cql tags==block:schema threads==1 cycles==UNDEF
    rampup: run driver=cql tags==block:rampup cycles===TEMPLATE(rampup-cycles,10) threads=auto
    main: run driver=cql tags=='block:main-.*' cycles===TEMPLATE(main-cycles,10) threads=auto

bindings:
  seq_key: Mod(<<keycount:1000000000>>); ToString() -> String
  seq_value: Hash(); Mod(<<valuecount:1000000000>>); ToString() -> String
  rw_key: <<keydist:Uniform(0,1000000000)->int>>; ToString() -> String
  rw_value: AlphaNumericString(1024); ToString() -> String

blocks:
  schema:
    ops:
      create-keyspace:
        raw: |
          create keyspace if not exists TEMPLATE(keyspace,baselines)
          WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 'TEMPLATE(rf,3)'}
          AND durable_writes = true;
      create-table:
        raw: |
          create table if not exists TEMPLATE(keyspace,baselines).TEMPLATE(table,keyvalue) (
          key text,
           value text,
           PRIMARY KEY (key)
          );
  schema-astra:
    ops:
     create-table:
      raw: |
        create table if not exists TEMPLATE(keyspace,baselines).TEMPLATE(table,keyvalue) (
        key text,
         value text,
         PRIMARY KEY (key)
        );
  rampup:
    params:
      cl: TEMPLATE(write_cl,LOCAL_QUORUM)
    ops:
      rampup-insert:
        prepared: |
          insert into TEMPLATE(keyspace,baselines).TEMPLATE(table,keyvalue)
          (key, value)
          values ({seq_key},{seq_value});
#  verify:
#    params:
#      cl: <<read_cl:LOCAL_QUORUM>>
#    ops:
#      verify-select:
#        prepared: |
#          select * from <<keyspace:baselines>>.<<table:keyvalue>> where key={seq_key};
#        verify-fields: key->seq_key, value->seq_value
  main-read:
    params:
      #ratio: 5
      cl: TEMPLATE(read_cl,LOCAL_QUORUM)
    ops:
      main-select:
        prepared: |
          select * from TEMPLATE(keyspace,baselines).TEMPLATE(table,keyvalue) where key={rw_key};
  main-write:
    params:
      #ratio: 5
      cl: TEMPLATE(write_cl,LOCAL_QUORUM)
    ops:
      main-insert:
        prepared: |
          insert into TEMPLATE(keyspace,baselines).TEMPLATE(table,keyvalue)
          (key, value) values ({rw_key}, {rw_value});

output
2024/1/16 19:44:37 =============================================================

-- Gauges ----------------------------------------------------------------------
bond0_rx_bytes
             value = 4.8708713148291E13
bond0_rx_packets
             value = 5.4582570646E10
bond0_tx_bytes
             value = 3.7548571619806E13
bond0_tx_packets
             value = 6.9119049476E10
cpu_idle
             value = 6.7051574557E10
cpu_iowait
             value = 4466667.0
cpu_system
             value = 5.3868814E7
cpu_total
             value = 6.7204622381E10
cpu_user
             value = 9.0910854E7
em1_rx_bytes
             value = 2.4261252225338E13
em1_rx_packets
             value = 2.7152609156E10
em1_tx_bytes
             value = 1.002764473E11
em1_tx_packets
             value = 2.03527331E8
em2_rx_bytes
             value = 2.4447460923277E13
em2_rx_packets
             value = 2.7429961495E10
em2_tx_bytes
             value = 3.7451031292228E13
em2_tx_packets
             value = 6.8915522145E10
em3_rx_bytes
             value = 0.0
em3_rx_packets
             value = 0.0
em3_tx_bytes
             value = 0.0
em3_tx_packets
             value = 0.0
em4_rx_bytes
             value = 0.0
em4_rx_packets
             value = 0.0
em4_tx_bytes
             value = 0.0
em4_tx_packets
             value = 0.0
lo_rx_bytes
             value = 1.911822662E9
lo_rx_packets
             value = 1.4064112E7
lo_tx_bytes
             value = 1.911822662E9
lo_tx_packets
             value = 1.4064112E7
loadavg_15min
             value = 0.21
loadavg_1min
             value = 1.39
loadavg_5min
             value = 0.37
main_read.input_cycle
             value = 100.0
main_read.input_cycles_first
             value = 0.0
main_read.input_cycles_last
             value = 100.0
main_read.input_cycles_total
             value = 0.0
main_read.input_recycle
             value = 40.0
main_read.input_recycles_first
             value = 0.0
main_read.input_recycles_last
             value = 1.0
main_read.input_recycles_total
             value = 0.0
main_read.ops_active
             value = 0.0
main_read.ops_complete
             value = 100.0
main_read.ops_pending
             value = 0.0
mem_available
             value = 6.8910488E7
mem_buffered
             value = 0.0
mem_cached
             value = 6070936.0
mem_free
             value = 6.9314064E7
mem_total
             value = 9.8717784E7
mem_used
             value = 2.940372E7
schema.input_cycle
             value = 2.0
schema.input_cycles_first
             value = 0.0
schema.input_cycles_last
             value = 2.0
schema.input_cycles_total
             value = 0.0
schema.input_recycle
             value = 1.0
schema.input_recycles_first
             value = 0.0
schema.input_recycles_last
             value = 1.0
schema.input_recycles_total
             value = 0.0
schema.ops_active
             value = 0.0
schema.ops_complete
             value = 2.0
schema.ops_pending
             value = 0.0
sda1_kB_read
             value = 88.0
sda1_kB_written
             value = 0.0
sda1_transactions
             value = 22.0
sda2_kB_read
             value = 28222.5
sda2_kB_written
             value = 2178.5
sda2_transactions
             value = 1250.0
sda3_kB_read
             value = 927026.0
sda3_kB_written
             value = 1.317471745E8
sda3_transactions
             value = 1.1207175E7
sda_kB_read
             value = 956376.5
sda_kB_written
             value = 1.31749353E8
sda_transactions
             value = 1.1208475E7
sdb1_kB_read
             value = 2.84179295365E10
sdb1_kB_written
             value = 618932.0
sdb1_transactions
             value = 1.17212491E8
sdb_kB_read
             value = 2.84179305725E10
sdb_kB_written
             value = 618932.0
sdb_transactions
             value = 1.17212518E8
sdc1_kB_read
             value = 8374656.5
sdc1_kB_written
             value = 35020.0
sdc1_transactions
             value = 490562.0
sdc_kB_read
             value = 8375692.5
sdc_kB_written
             value = 35020.0
sdc_transactions
             value = 490589.0
swap_free
             value = 0.0
swap_total
             value = 0.0
swap_used
             value = 0.0

-- Counters --------------------------------------------------------------------
main_read.optracker_blocked
             count = 0
schema.optracker_blocked
             count = 0

-- Histograms ------------------------------------------------------------------
main_read.main-read__main-select.pages
             count = 100
main_read.main-read__main-select.payload_bytes
             count = 100
main_read.main-read__main-select.rows
             count = 100
main_read.tries
             count = 100
schema.schema__create-keyspace.pages
             count = 1
schema.schema__create-keyspace.payload_bytes
             count = 1
schema.schema__create-keyspace.rows
             count = 1
schema.schema__create-table.pages
             count = 1
schema.schema__create-table.payload_bytes
             count = 1
schema.schema__create-table.rows
             count = 1
schema.tries
             count = 2

-- Timers ----------------------------------------------------------------------
main_read.bind
             count = 100
main_read.cycles_servicetime
             count = 100
main_read.execute
             count = 100
main_read.main-read__main-select.verifier
             count = 0
main_read.read_input
             count = 140
main_read.result
             count = 100
main_read.result_success
             count = 100
main_read.strides_servicetime
             count = 100
main_read.verifier
             count = 100
schema.bind
             count = 2
schema.cycles_servicetime
             count = 2
schema.execute
             count = 2
schema.read_input
             count = 2
schema.result
             count = 2
schema.result_success
             count = 2
schema.schema__create-keyspace.verifier
             count = 0
schema.schema__create-table.verifier
             count = 0
schema.strides_servicetime
             count = 1
schema.verifier
             count = 2

2024/1/16 19:44:39 =============================================================

-- Gauges ----------------------------------------------------------------------
bond0_rx_bytes
             value = 4.8708713153505E13
bond0_rx_packets
             value = 5.4582570719E10
bond0_tx_bytes
             value = 3.7548571624492E13
bond0_tx_packets
             value = 6.9119049547E10
cpu_idle
             value = 6.7051579646E10
cpu_iowait
             value = 4466667.0
cpu_system
             value = 5.3868819E7
cpu_total
             value = 6.7204627701E10
cpu_user
             value = 9.091108E7
em1_rx_bytes
             value = 2.4261252228278E13
em1_rx_packets
             value = 2.7152609197E10
em1_tx_bytes
             value = 1.00276448158E11
em1_tx_packets
             value = 2.03527344E8
em2_rx_bytes
             value = 2.4447460925623E13
em2_rx_packets
             value = 2.7429961528E10
em2_tx_bytes
             value = 3.7451031296122E13
em2_tx_packets
             value = 6.8915522204E10
em3_rx_bytes
             value = 0.0
em3_rx_packets
             value = 0.0
em3_tx_bytes
             value = 0.0
em3_tx_packets
             value = 0.0
em4_rx_bytes
             value = 0.0
em4_rx_packets
             value = 0.0
em4_tx_bytes
             value = 0.0
em4_tx_packets
             value = 0.0
lo_rx_bytes
             value = 1.911822662E9
lo_rx_packets
             value = 1.4064112E7
lo_tx_bytes
             value = 1.911822662E9
lo_tx_packets
             value = 1.4064112E7
loadavg_15min
             value = 0.21
loadavg_1min
             value = 1.39
loadavg_5min
             value = 0.37
main_read.input_cycle
             value = 100.0
main_read.input_cycles_first
             value = 0.0
main_read.input_cycles_last
             value = 100.0
main_read.input_cycles_total
             value = 0.0
main_read.input_recycle
             value = 40.0
main_read.input_recycles_first
             value = 0.0
main_read.input_recycles_last
             value = 1.0
main_read.input_recycles_total
             value = 0.0
main_read.ops_active
             value = 0.0
main_read.ops_complete
             value = 100.0
main_read.ops_pending
             value = 0.0
mem_available
             value = 6.89079E7
mem_buffered
             value = 0.0
mem_cached
             value = 6071076.0
mem_free
             value = 6.9311408E7
mem_total
             value = 9.8717784E7
mem_used
             value = 2.9406376E7
schema.input_cycle
             value = 2.0
schema.input_cycles_first
             value = 0.0
schema.input_cycles_last
             value = 2.0
schema.input_cycles_total
             value = 0.0
schema.input_recycle
             value = 1.0
schema.input_recycles_first
             value = 0.0
schema.input_recycles_last
             value = 1.0
schema.input_recycles_total
             value = 0.0
schema.ops_active
             value = 0.0
schema.ops_complete
             value = 2.0
schema.ops_pending
             value = 0.0
sda1_kB_read
             value = 88.0
sda1_kB_written
             value = 0.0
sda1_transactions
             value = 22.0
sda2_kB_read
             value = 28222.5
sda2_kB_written
             value = 2178.5
sda2_transactions
             value = 1250.0
sda3_kB_read
             value = 927026.0
sda3_kB_written
             value = 1.317471745E8
sda3_transactions
             value = 1.1207175E7
sda_kB_read
             value = 956376.5
sda_kB_written
             value = 1.31749353E8
sda_transactions
             value = 1.1208475E7
sdb1_kB_read
             value = 2.84179295365E10
sdb1_kB_written
             value = 618932.0
sdb1_transactions
             value = 1.17212491E8
sdb_kB_read
             value = 2.84179305725E10
sdb_kB_written
             value = 618932.0
sdb_transactions
             value = 1.17212518E8
sdc1_kB_read
             value = 8374656.5
sdc1_kB_written
             value = 35020.0
sdc1_transactions
             value = 490562.0
sdc_kB_read
             value = 8375692.5
sdc_kB_written
             value = 35020.0
sdc_transactions
             value = 490589.0
swap_free
             value = 0.0
swap_total
             value = 0.0
swap_used
             value = 0.0

-- Counters --------------------------------------------------------------------
main_read.optracker_blocked
             count = 0
schema.optracker_blocked
             count = 0

-- Histograms ------------------------------------------------------------------
main_read.main-read__main-select.pages
             count = 100
main_read.main-read__main-select.payload_bytes
             count = 100
main_read.main-read__main-select.rows
             count = 100
main_read.tries
             count = 100
schema.schema__create-keyspace.pages
             count = 1
schema.schema__create-keyspace.payload_bytes
             count = 1
schema.schema__create-keyspace.rows
             count = 1
schema.schema__create-table.pages
             count = 1
schema.schema__create-table.payload_bytes
             count = 1
schema.schema__create-table.rows
             count = 1
schema.tries
             count = 2

-- Timers ----------------------------------------------------------------------
main_read.bind
             count = 100
main_read.cycles_servicetime
             count = 100
main_read.execute
             count = 100
main_read.main-read__main-select.verifier
             count = 0
main_read.read_input
             count = 140
main_read.result
             count = 100
main_read.result_success
             count = 100
main_read.strides_servicetime
             count = 100
main_read.verifier
             count = 100
schema.bind
             count = 2
schema.cycles_servicetime
             count = 2
schema.execute
             count = 2
schema.read_input
             count = 2
schema.result
             count = 2
schema.result_success
             count = 2
schema.schema__create-keyspace.verifier
             count = 0
schema.schema__create-table.verifier
             count = 0
schema.strides_servicetime
             count = 1
schema.verifier
             count = 2

**Comment by jshook** [comment]
In order to get metrics which depend on a statistically significant number of samples, you have to run the activity long enough to complete a metrics sampling window. Otherwise, these metrics are terribly misleading, thus they are only emitted in session summaries which are not substantial enough to be stable.  This is also an issue because of cold-start effects on systems, as with JVM/JIT, etc.

You will get all the data you are looking for by running with `--report-csv-to adirectory`, but I strongly advise you run a longer test before trusting any response data.
