### ISSUE TITLE
Schema-driven workload generation for CQL

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#181]
Allow for the construction of a default workload based on an accessible or provided schema.

Initially, this will be provided for the CQL driver and possibly adapted to other drivers as appropriate.

This means taking an existing schema as the basis for some supposed set of operations. There are many possibilites to consider in terms of mapping schema to operations, but this plan only considers the most basic possible operations which can exercise a schema:

- write data to a database given a schema - Construct insert operations using very basic and default value generation for the known row structure
- read data to a database, given a schema - Construct read operations using very basic and default value generation for the known identifier structure

Users should be allowed to specify which keyspaces and/or tables should be included.

Users will be allowed to specify the relative cardinality of values used at each level of identifier, and the type of value nesting.

The source of the schema will be presumed to be a live system, with the workload generation being done on-the-fly, but with an option to save the workload description instead of running it. In the case of running the workload, the option to save it will be allowed additionally.

The option to provide the schema as a local file (a database dump of describe keyspace, for example) should be provided as an enhancement.

This is a stepping stone towards full workload synthesis using schema and operational logs. For more details on the rationale and approach for that, see the [workload synthesis](https://github.com/nosqlbench/nosqlbench/blob/nosqlbench-3.12.134/devdocs/sketches/workload_synthesis.md) design sketch.

**Comment by dave2wave** [comment]
Is this now #783 ?

**Comment by dave2wave** [comment]
This is CQLGen
