### ISSUE TITLE
Improvements for OSHI SystemInfo

### ISSUE THREAD

**Issue by dbwiddis** [nosqlbench/nosqlbench#187]
**Describe the bug**
The calculation for frequency in `engine/api/activityimpl/CpuInfo.java` assumes binary units rather than decimal, and doesn't handle the API's negative return values.

**To Reproduce**
1. Get the CPU frequency from from `getMhz()`
2. Compare it to the frequency in `/proc/cpuinfo` or `lscpu`.

**What was Expected**
Frequency should match. Instead it's a lower value.

**Additional context**
I'm the author of OSHI and I periodically check to see other projects which use the dependency.  I've noted a few things in your `CpuInfo` class that I'd like to help you fix.  Happy to submit a PR but wanted your feedback first.
 - Line 65: You incorrectly divide by 1024 * 1024 instead of 1000 * 1000. MHz is a decimal unit.  Per the comment, the Max Frequency may not be what you want, as it can include the higher "Turbo Boost" frequency on some OS's.  Current Frequency (one value per logical processor) may sometimes be too low if your system throttles CPU.  You might wish to use Vendor frequency (`processor.getProcessorIdentifier().getVendorFreq()`) which is the advertised frequency of the chip as seen in the processor identifier string. While this may give you "speed" in excess of 100% I think that better represents the metric.
 - Line 87: You handle `Double.NaN` which will never occur.  The `get*Freq()` methods return -1 on failure, so you should either do a `> 0` check in your methods on line 77 and line 80 (and return `NaN` there), or replace the `NaN` checks on line 87 with `> 0` checks.
 - POM Version:  OSHI has a transitive dependency on JNA, which requires 5.6.0 or later for compatibility with the upcoming macOS 11 (Big Sur).  Updating to the latest version of OSHI (presently 5.2.2, or 4.9.2 if you wish to stay on the 4.x branch) will automatically include this transitive dependency, otherwise you should specify it yourself.

**Comment by jshook** [comment]
@dbwiddis Thanks for looking into our project!
These are fairly easy fixes and well documented above. I'll mark these as easy picks for now. If you wanted to submit a PR, we certainly like those. However the impact to the project is low for now until we activate these call paths in upcoming work.

The plan is to use OSHI first for documenting scenario execution details, and after for resource/headroom sanity checks.

**Comment by dbwiddis** [comment]
I'll leave this for easy-picks then.  And yes, there's a lot more resource info available than what you're using so far, feel free to ping me if you need any help integrating.

**Comment by jshook** [comment]
The changes above have been made. Thanks for the help, @dbwiddis ! The code isn't fully active yet, but sooooon.
