### ISSUE TITLE
Ensure positional parameters in global options are treated uniformly.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#19]
Some arguments to the main CLI and activity parameters are used to install an optional component, which has its own initialization properties. An example of this is the set of metrics reporting options which follow a
`--log-histograms 'histodata.log:.*specialmetrics:10s'`
pattern where you can specify either `logfile`, `logfile:filter` or `logfile:filter:interval`.

The ability to pass a set of initialization parameters by name is needed across optional components so that the pattern remains familiar and self-explanatory to users. All "sub parameter' semantics should be converted to use this new API. 

To address this:
- [x] Review NBCLIOptions and ensure that positional sub-parameter parsing uses common code.
- [x] Add unit tests for coverage

**Comment by jshook** [comment]
This issue should be discarded, since this falls within the scope of an initiative which will likely leverage the picocli library for defining parameter conventions.

**Comment by dave2wave** [comment]
There is a subclass here: https://github.com/nosqlbench/nosqlbench/blob/main/nb-engine/nb-engine-cli/src/main/java/io/nosqlbench/engine/cli/NBCLIOptions.java#L1059

**Comment by dave2wave** [comment]
The work here is to add a unit test to https://github.com/nosqlbench/nosqlbench/blob/main/nb-engine/nb-engine-cli/src/test/java/io/nosqlbench/engine/cli/TestNBCLIOptions.java
