### ISSUE TITLE
Logging runtime needs updated

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#191]
Logging needs to be consolidated to a single runtime implementation.
- SLF4J needs to be removed.
- Logback needs to be removed.
- Log4J 2 needs to be used throughout.
- Programmatic constructions on Logback need to be reimplemented with Log4j
- Parent pom needs to explicitly pull in logging dependencies
- All depending modules need to remove logging configurations.
- All body arguments for calls in log4j should be converted to lambdas and tested for performance changes

**Comment by dave2wave** [comment]
This appears to have been partially completed and may be to the point of mvn pom.xml file cleanup.
