### ISSUE TITLE
Handle commented-out template variables work as expected.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1927]
In any case, nosqlbench should understand if a template variable occurs within a commented line of YAML, so that it may provide appropriate feedback for corner cases.

This should use the validation settings from #12 

In the relaxed mode, the presence of unused (commented-out) template variables should not matter, but if there is a discrepancy, the user should get a warning.

In the assertive mode, if a template variable is commented out in every position, yet it is still provided, then this should be considered an error, and the user informed of the details. Template variables which are used in at least one position (not commented out) should not be considered an error.

**Comment by dave2wave** [comment]
The Advisor would be checking for template functions in comments that set the parameter value to a new default value. 

Following every case to see if the parameter default is provided and not used is a different use case.

IMO allowing parameter setting in a comment is a feature and not a bug.

**Comment by dave2wave** [comment]
Just ignore commented lines.
