### ISSUE TITLE
Add ability to generate Avro formatted messages in kafka driver

### ISSUE THREAD

**Issue by ncarvind** [nosqlbench/nosqlbench#196]
**What is the ideal scenario for using this feature?**
A lot of projects use a serialization format for messages produced into Kafka. Avro is very popular among the serialization formats.

**Is your feature request related to a problem? Please describe.**
No

**Would you like to help implementing or testing it?**
I can help test it.

**Additional context**

**Comment by jshook** [comment]
@ncarvind What was your finding on whether this should be done at the app level or in a kafka config?

**Comment by ncarvind** [comment]
@jshook It needs to be done at the app.

**Comment by ncarvind** [comment]
Fixed with https://github.com/nosqlbench/nosqlbench/pull/208
