### ISSUE TITLE
Pre-check auto-download sizes and verify target filesystem has room

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1969]
When using the NBIO cache, it is possible to easily overfill file systems which are not already configured for storing testing assets, such as small default root volumes on cloud instances.

We should move detection of this up to the beginning of the download. It is possible to see the what the downloaded size would be with a simple HEAD request which gives:

```
HTTP/1.1 200 OK
[extraneous headers redacted]
Date: Wed, 26 Jun 2024 15:39:28 GMT
Last-Modified: Thu, 11 Apr 2024 20:47:40 GMT
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Content-Length: 12426888192
```

The content length can then be checked against the filesystem remaining size for the target volume.

**Comment by MarkWolters** [comment]
implemented in https://github.com/nosqlbench/nosqlbench/commit/e29f3d8719ff2e2a8b5bc45bcc7208402acfb859
