### ISSUE TITLE
Use latest dockers, but allow tags to be provided.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#197]
The --docker-metrics support should not be limited to a specific version, as some docker release trains move quickly and expire specific versions over time. Instead, the latest stable release should be reference by name.
This is for the grafana, docker, and graphite exporter dockers images.

However, some users may want to limit impact to their docker stack in such case that using the latest release causes issues. For this, we should allow docker tags be provided for each of these.

The docker grafana tag can already by the `--docker-grafana-tag` option. This works as an example for the others, so this issue will be marked as easy pick.

**Comment by dave2wave** [comment]
perhaps this a requirement

**Comment by jshook** [comment]
This is superseded by a new approach to be documented in a separate issue.
