### ISSUE TITLE
Add Docs example on running against Astra

### ISSUE THREAD

**Issue by ErickRamirezDS** [nosqlbench/nosqlbench#198]
**What is the ideal scenario for using this feature?**
There isn't an example that can be easily found by users.

**Is your feature request related to a problem? Please describe.**
No.

**Would you like to help implementing or testing it?**
Yes.

**Additional context**
We should make it easier for users to find an example command like this:

```
$ nb run driver=cql \
    workload=cql-iot \
    tags=phase:schema \
    username=astra_user \
    password=astra_password \
    secureconnectbundle=/path/to/secure-connect-mydatabase.zip
```

**Comment by ds-steven-matison** [comment]
The only documentation reference i found here was in [cql.md](http://docs.nosqlbench.io/#/docs/drivers/cql.md).   I can add this example but maybe an astra page or other area is more appropriate?   

Updated cql.md commit on my fork:
https://github.com/ds-steven-matison/nosqlbench/commit/909e7609ffdd20fa6a139207d545a7e89a949632

**Comment by ds-steven-matison** [comment]
We did a link to astra documentation here.  I worked with internal resources on the astra side to get a page created for nosqlbench.  Crosslinking FTW!

https://docs.astra.datastax.com/docs/test-loading-data-with-nosqlbench

PR: https://github.com/nosqlbench/nosqlbench/pull/243

@erickramirezDSE  you can close this Issue please?
