### ISSUE TITLE
PromPush Reporter with `victoria:` will not connect via http

### ISSUE THREAD

**Issue by dave2wave** [nosqlbench/nosqlbench#1983]
**Describe the bug**
Simple VictoriaMetrics local configurations are typically http and not https. This means that `--report-prompush-to victoria:34.100.192.129:8428` will fail.

**To Reproduce**
1. Run against a basic docker setup with:
   ```bash
   java -jar nb5.jar wati-driver default.rampup --report-prompush-to victoria:34.100.192.129:8428 scb=$ASTRA_DB_BUNDLE_PATH username=$ASTRA_DB_CLIENT_ID password=$ASTRA_DB_CLIENT_SECRET cyclerate=4000 --show-stacktraces --progress console:1s
   ```
2. You will get an error:
   ```
   ERROR [REPORT-PROMPUSH] PromPushReporterComponent [javax.net](http://javax.net/).ssl.SSLException: Unrecognized SSL message, plaintext connection
   ```

**What was Expected**
The `victoria:` form should be able to know from the port whether to use `https` or `http`.

**Comment by jshook** [comment]
I would like for us to be able to specifically set the scheme, even if we default to http or https based on the port. This would allow users to override in the case that the port number was not one of the defaults for victoria.

**Comment by dave2wave** [comment]
> I would like for us to be able to specifically set the scheme, even if we default to http or https based on the port. This would allow users to override in the case that the port number was not one of the defaults for victoria.

Then what is the advantage of `victoria:` compared to `http://` and `https://`?

One possibility is
