### ISSUE TITLE
Users should be able to specify sensitive activity parameters like passwords indirectly and uniformly.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1985]
We have the convention of supporting userfile as well as username and passfile as well as passname, but these are spot treatments in each place they are enabled. There should be a way to do this for any activity parameter using a basic syntax.

Atfile `@somefile.yaml` support can help here, but this is not as simple as it could be. The `@` character is often annoying to deal with in shells. Instead, we may want to support a prefix on the value such as `from:` which will work for any possible value.

**Comment by dave2wave** [comment]
Would a property file and then injection via `${myprops.password}`be a better approach? The property file key/values can be attached to the NBEnvironment class and be interpolated in the same places easily. In workloads I think that `TEMPLATE(myprops.password)` and `<<myprops.password>>` would work. I think that having these as global and cumulative would be an ok UX.

**Comment by dave2wave** [comment]
This `user/password` pattern is only found in `Cqld4Space.java` and `Neo4JSpace.java`. `DataApiSpace.java` uses `endpointfile`. Several of other adapters use `token_file` and `token`.

It would be good to have a utility method. We should discuss @jshook

**Comment by dave2wave** [comment]
One suggestion to solve this is to allow the password / token parameters to retrieve the value using a prefix like "file:<path_to_token_file>". This is complementary with #375

**Comment by dave2wave** [comment]
The other part is making sure we can never expose these parameters in logs.

Parameter names interface in `ActivityDef` can somehow know which type of parameter. We need to know the purpose of the "`ToString`" and then know when to mask the value.

**Comment by dave2wave** [comment]
Part of the Advisory function should be to redirect users towards using the preferred option.

**Comment by dave2wave** [comment]
The ask of this issue is still nebulous:
1. Is this about adding support for properties files like "AtFiles"?
2. Is this about @ being difficult? If so, then `include=` is an alternative.
3. Is this about allowing any `value` in a key-value command line argv being expandable with the value found in a file?

**Comment by dave2wave** [comment]
4. Is this about "knowing" which parameters are sensitive and making sure that these are not easily exposed in logging, etc?
