### ISSUE TITLE
Act Properly When a Known Adapter is Missing From The Build 

### ISSUE THREAD

**Issue by dave2wave** [nosqlbench/nosqlbench#2001]
**What is the ideal scenario for using this feature?**
I want to run a workload the uses an adapter that was not included in the jar. The action or messaging for this case should explain (or point to an explanation) of how to either build for this adapter or even better how to get a build and load it.

**Is your feature request related to a problem? Please describe.**
When a user upgrades from a prior version and tries to use an excluded adapter like Kafka they don't get a quick and helpful error message with clear instructions.

**Comment by jshook** [comment]
Suggestions:
1) When an adapter is asked for which is not present in the runtime, we should inform the user about how some optional adapters are not always included.
2) We should also have a link to a docs page that explains how modular adapters work within the build and runtime.

**Comment by dave2wave** [comment]
It seems that #1933 was reverted and moved to `StandardActivity.java`

**Comment by dave2wave** [comment]
#2083 provides instructions
