### ISSUE TITLE
Out of box examples missing

### ISSUE THREAD

**Issue by JFlowx** [nosqlbench/nosqlbench#2045]
**Describe the bug**

I followed the getting started doc, installed the nb5 binary and tried to run the command ./nb5 examples/bindings-basics
Got the following error -  1512 ERROR [main] ERRORHANDLER Could not recognize command 'examples/bindings-basics'

Seems like there should be some directories for the examples and activities but they do not appear to have come with the binary download. Didn't see anything in the getting started doc saying to download those separately either.

Thanks for the help!

**To Reproduce**
1. Install nb5 binary, run the following command ./nb5 examples/bindings-basics

**What was Expected**
The command should have run successfully.

**Additional context**
Ubuntu 24.04 LTS 
Vm running on vmware

**Screenshots, if applicable**
If applicable, add scre
![NoSQLBenchError](https://github.com/user-attachments/assets/706992f7-ca6d-4597-b4ef-9b2cdad42a33)
enshots to help explain your problem.

**Comment by msmygit** [comment]
Hi there!

The error, as it states, it couldn't find `examples/bindings-basics` (notice the hypen character. we'll talk about here in a second).

I'd try the below `--list-workloads` which is shown as output from running `--list-scenarios`. Now that the workload we're interested is in `examples`, I'd add `--include=examples` and here is what I find out,
```
% nb521 --list-workloads --include=examples --show-stacktraces|grep bindings
/activities/examples/bindings/cqlvectors.yaml
/examples/bindings_basics.yaml
/examples/bindings_bigdecimal.yaml
/examples/bindings_bytebuffers.yaml
/examples/bindings_charbuffers.yaml
# examples of collections bindings
/examples/bindings_collections.yaml
/examples/bindings_cqlvectors.yaml
# examples of bindings that produce doubles
/examples/bindings_double.yaml
# examples of bindings that produce long values as epoch millis
/examples/bindings_epochmillis.yaml
# examples of premade bindings
/examples/bindings_premade.yaml
/examples/bindings_probcurves.yaml
# examples of bindings that help you diagnost binding recipes
/examples/bindings_utilities.yaml
/examples/bindings_vectors.yaml
```
which gives me all the workloads available. And, we need `/examples/bindings_basics.yaml`. As a next step, I'd run the below command. Here I'm restricting the `cycles=20` because I don't want to 

```
% nb521 examples/bindings_basics.yaml cycles=20 --show-stacktraces
escaped : "quotes included!"
 lambda : pre-0-post
   name : zero
   show : {}
      n : 0
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-1-post
   name : one
   show : {}
      n : 1
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-2-post
   name : two
   show : {}
      n : 2
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-3-post
   name : three
   show : {}
      n : 3
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-4-post
   name : four
   show : {}
      n : 4
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-5-post
   name : five
   show : {}
      n : 5
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-6-post
   name : six
   show : {}
      n : 6
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-7-post
   name : seven
   show : {}
      n : 7
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-8-post
   name : eight
   show : {}
      n : 8
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-9-post
   name : nine
   show : {}
      n : 9
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-10-post
   name : ten
   show : {}
      n : 10
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-11-post
   name : eleven
   show : {}
      n : 11
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-12-post
   name : twelve
   show : {}
      n : 12
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-13-post
   name : thirteen
   show : {}
      n : 13
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-14-post
   name : fourteen
   show : {}
      n : 14
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-15-post
   name : fifteen
   show : {}
      n : 15
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-16-post
   name : sixteen
   show : {}
      n : 16
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-17-post
   name : seventeen
   show : {}
      n : 17
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-18-post
   name : eighteen
   show : {}
      n : 18
 typeof : java.lang.String

escaped : "quotes included!"
 lambda : pre-19-post
   name : nineteen
   show : {}
      n : 19
 typeof : java.lang.String

stdout (pending,current,complete)=(0,0,20) 100.00% (last report)
```

I hope that helped. Cheers!

**Comment by JFlowx** [comment]
Thank you for your reply,

I was able to run the commands you did and got the same output, however I am still not able to run the basic commands listed in the getting started doc

./nb5 examples/bindings-basics


./nb5 examples/bindings-basics default


./nb5 examples/bindings-basics default \
 filename=exampledata.out \
 format=csv \
 cycles=10000 \
 rate=100 \
 --progress console:1s


I also tried adding .yaml to the end of examples/bindings-basics and still not working with the same error message...

![NoSQLBenchError- yaml](https://github.com/user-attachments/assets/edccfd4c-7c27-4069-bd6d-77a8f2ac5d87)

**Comment by dave2wave** [comment]
To resolve this issue we need to update the documentation.

**Comment by dave2wave** [comment]
#2080 is a clearer response to the underlying issue here.
