### ISSUE TITLE
NBUI: Bindings visualizer

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#205]
A user should be able to construct a binding recipe in an incremental and interactive way.

## Elements

Basic elements of the of the bindings visualizer should include:
- Type specific dropdown list of available binding recipes from all known yamls.
- An option to enable strict type matching between functions (on by default), or to allow for auto-conversion where needed.
- The ability to name, describe, and add the current binding under construction to a named bindings set.
- visualization section which allows for a user to see dynamically what the bindings look like
- Input selector panel, a set of inputs to try, or a selection of pre-defined ranges

## Visualizations

- Binding execution summary, execution times, total executions, average time per binding
- Data display, a readout of values produced by a binding
- Distribution plot, a way to see the distribution of values

**Comment by dave2wave** [comment]
NBUI is no longer supported.
