### ISSUE TITLE
Slack invite form doesn't work

### ISSUE THREAD

**Issue by szimmer1** [nosqlbench/nosqlbench#219]
**Describe the bug**
I tried filling the [Slack invite form](https://docs.google.com/forms/d/e/1FAIpQLSdUOJ8iAPqyxsLfh1nBBsKShI53RAeuzYW4bKExmRMWjj4ufQ/viewform) over a day ago. Also tried a different email about an hour ago. Haven't received an email invite to either address (checked spam, etc).

Looking forward to joining the conversation and further evaluating the features!

**Comment by jshook** [comment]
@szimmer1 The link was changed recently to be a direct invite link, since the slack API that was used with the form is being deprecated. Can you go back to the "Getting Support" link on the docs site and see if that is the new link for you?
If not, a forced refresh of the docs site might fix it in your browser. 

Either way, if you could please let me know what you find so I know whether to close this ticket.

**Comment by szimmer1** [comment]
The link in the getting support [page](http://docs.nosqlbench.io/#/docs/nosqlbench/getting_support.md) seems to be expired. See attached screenshot. I also tried to join at https://nosqlbench.slack.com/signup#/ but it looks restricted to @datastax.com email domain.
<img width="678" alt="Screen Shot 2020-10-06 at 4 15 40 PM" src="https://user-images.githubusercontent.com/8455475/95269941-5f288000-07ef-11eb-879c-402f2bf12f43.png">

**Comment by jshook** [comment]
Try this link, which is directly from the workspace settings, and is
flagged as good for 25 more days:
https://join.slack.com/t/nosqlbench/shared_invite/zt-hvavu1tu-CLX_w7plZrv_A8kDBCw_3A

**Comment by jshook** [comment]
Honestly, Slack has made it so difficult for OSS projects to manage this,
that I'm seriously considering moving the chat to Discord, which just
recently opened up their options more to support community servers.

I'll run it by the current members too, but I suspect that there may be
more of us in slack for work reasons and thus less inclined to jump to
discord for this. We'll see after taking a straw poll.

**Comment by jshook** [comment]
If this link doesn't work, I'll manually cycle the invite link and update the docs for it.

**Comment by szimmer1** [comment]
That worked, thanks. Agreed Slack has more synergy than Discord. I joined the channel, but I'll leave this issue open.

**Comment by szimmer1** [comment]
Closed since we're on Discord
