### ISSUE TITLE
we are getting the status of the /tmp...mount point as below after the load process is abruptly killed

### ISSUE THREAD

**Issue by manvishan** [nosqlbench/nosqlbench#229]
df: '/tmp/.mount_nb_binHpzeqg': Transport endpoint is not connected

especially when we kill the process

can we change this location to any custom path?

**Comment by jshook** [comment]
This indicates some type of problem with how AppImage is trying to run on your system.
AppImage is how we package the binary version.

The best place to look for info on this is here: https://docs.appimage.org/user-guide/run-appimages.html
There is also a troubleshooting section in the same place.

Let me know if this gets you running?

**Comment by manvishan** [comment]
many thanks. It worked
