### ISSUE TITLE
Metrics instances should be grouped hierarchically

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#234]
NB internal APIs have some support for aggregating metrics registry views.
This should be used to logically group metrics instances into named registries so that individual activities can each have a specific and cohesive view of metrics. This would allow users to see metrics only for the activities they are interested in, during a session ,or in reports. It would also allow for saner logical grouping metrics when displayed.

**Comment by dave2wave** [comment]
This is done and working well in MB 5.21. It might not be exactly as described but poper labeling of metrics allows for this separation.
