### ISSUE TITLE
Dockerfile and published image still use Java 14

### ISSUE THREAD

**Issue by XN137** [nosqlbench/nosqlbench#236]
**Describe the bug**
Dockerfile uses java 14:
https://github.com/nosqlbench/nosqlbench/blob/e4f325c43bf39948af925da5caaf94ced5a05112/Dockerfile#L1

yet in 7e6aa1a2d86fe29240efbbaa54e0c34bff178e9f the target version was changed to java 15.

the newly published "latest" image on dockerhub fails to run with:
```
Error: LinkageError occurred while loading main class io.nosqlbench.engine.cli.NBCLI
	java.lang.UnsupportedClassVersionError: io/nosqlbench/engine/cli/NBCLI has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 58.0
```
https://hub.docker.com/layers/nosqlbench/nosqlbench/latest/images/sha256-797aae730911dc8707f93589a9e3eaa972b0ee0839640245f8518520333b49fb?context=explore

**Comment by XN137** [comment]
some ideas in addition to fixing the obvious problem in the Dockerfile:
- smoke test docker images before publishing somehow
- maybe also publish a `3.12_latest` tag or the like for each major version (but maybe 3.12.x is discontinued since 4.0.x has no breaking changes? idk)

**Comment by jshook** [comment]
I am stabilizing the NB3 release integration. The Java 15 inclusion was accidental. It was meant for the NB4 branch, but somehow I missed it.

For now, I have changed NB 3* to use Java 11 as source and target in the project, with J14 as the runtime in docker and appimage. NB4* will use Java 15 by default across the board to allow for usage of the newer java features at the language level. If there is a strong push back on this, we can consider rolling it back, but at the cost of holding back progress on new features which may be important for performance and simplicity.

I'm setting up the build pipeline to avoid tagging NB4 with any /latest tags. Before it goes live, we'll make it version specific.

**Comment by jshook** [comment]
I'm also adding a sanity check to the github actions for docker before it is pushed.

**Comment by jshook** [comment]
Closing this issue as the primary issue has been resolved. However, I'll open a couple more to cover some gaps:
1) always logging version at 'INFO'
2) ensure that a '3x' tag is available in docker before nb4 becomes the latest

**Comment by XN137** [comment]
thank you for the quick reponse/fix!
