### ISSUE TITLE
Improve CLI Documentation Topics

### ISSUE THREAD

**Issue by ds-steven-matison** [nosqlbench/nosqlbench#237]
It came up in Slack that SSL documentation and CLI options are missing or hard to find.

```
% java -jar nb.jar help topics     
# global help topics
- commandline
- cli-scripting
```

Suggest improving the intial  help call to expose all help topics.  For example:

help cql
help ssl
etc

Update corresponding documentation markdown.

**Comment by ds-steven-matison** [comment]
404: http://docs.nosqlbench.io/services/docs/drivers/ssl.mdundefined

**Comment by ds-steven-matison** [comment]
@jshook I dug into code and verify that ssl.md is correctly located in driver-cql-shaded/src/main/resources.

Can you help with why "undefined" is appended during the markdown translation?

**Comment by ds-steven-matison** [comment]
Added ssl topic to:

/Users/stevenmatison/Documents/GitHub/nosqlbench-fork/engine-cli/target/classes/topics.md:

/Users/stevenmatison/Documents/GitHub/nosqlbench-fork/engine-cli/src/main/resources/topics.md:


This is on my fork until have enough documentation adjustments to warrant a PR.

**Comment by ds-steven-matison** [comment]
@jshook  Are there are other topics I can add while this is open?

**Comment by ds-steven-matison** [comment]
Added ssl and tested:

`% java -jar nb.jar help topics         
# global help topics
- commandline
- cli-scripting
- ssl
`

Update commit on my fork:
https://github.com/ds-steven-matison/nosqlbench/commit/bf51056fce58b7b8ee540d0490d1db1d16c5f49c

**Comment by ds-steven-matison** [comment]
Looks like topic "cql"  could be added too..

**Comment by jshook** [comment]
cql is listed under the driver types. It should be automatically populated into the docs site.

Example: [cql](http://docs.nosqlbench.io/#/docs/drivers/cql.md)

**Comment by ds-steven-matison** [comment]
PR for this one:  https://github.com/nosqlbench/nosqlbench/pull/243
