### ISSUE TITLE
Provide data lifecycle automation tooling

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#249]
It would be useful to be able to sequence and gate test stages on external APIs for staging data on a system.
This could include, for example, calls to s3, to move datasets around on different nodes.

This should be modeled as a set of declarative assertions which imply idempotent commands to bring a system to a known state.
Ideally, this would be provided by a library or javascript extension that could be bundled with the runtime on an ad-hoc basis.
This would allow the test tooling to adapt to different environments with different authentication schemes, etc.

**Comment by dave2wave** [comment]
Too much and too ambiguous.
