### ISSUE TITLE
Enhancement: Provide finer grained progress feedback regardless of stride or concurrency

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#267]
"My progress has stopped working.  It is always giving a 100.00%/Starting no matter how many cycles I give it (i.e. 100K or 10M)."

This could be a bug or it could be because of how strides work with ratios. If the stride is very high, then the per-thread allocation of cycles might cause the progress meter to be advanced to complete while one or a few threads works through the sequence.

**Comment by jshook** [comment]
Follow up: This appears to have been related to the stride and sequence length with low thread counts. The visibility of this should be elevated at least, and perhaps the progress tracker should be finer-grained.

**Comment by dave2wave** [comment]
Fine grained metrics has solved this issue.
