### ISSUE TITLE
nosqlbench does not show any progress on the screen

### ISSUE THREAD

**Issue by nikhilsk99** [nosqlbench/nosqlbench#298]
ubuntu@ip-172-31-38-16:~/nosqlbench$ ./nb --version
4.15.32
ubuntu@ip-172-31-38-16:~/nosqlbench$

Command used 
ubuntu@ip-172-31-38-16:~/nosqlbench$ ./nb run type=cql yaml=my.yaml tags=phase:rampup username=cassandra password=cassandra  threads=30x strides=150  cycles=200m..300m --progress console:60s numberofad=4 host=3.60.248.3 pooling=3:3:1500

I used the flag --progress console:60s , I was expecting to see the progress on the screen but didn't.

**Comment by dave2wave** [comment]
No longer valid.
