### ISSUE TITLE
Arg parsing broken since v4.15.33 - unrecognized option

### ISSUE THREAD

**Issue by grighetto** [nosqlbench/nosqlbench#308]
**Describe the bug**

Passing a scenario name to the nb command with the Docker image fails with: `ScenarioErrorHandler internal error: unrecognized option:target` where `target` is my scenario name.
The scenario name is also templated in my workload yaml like this `TEMPLATE(scenarioname,default)` and it's passed as an arg like this `scenarioname=target`. Full command below.
I'm not sure if templating the the scenario name is related, but I'm mentioning it for completeness.
The same command works in v4.15.32.

**To Reproduce**

1. Make the scenario name templated in the YAML with:

```
scenarios:
    TEMPLATE(scenarioname,default):
```

2. Execute NB from the Docker image with the following command-line args:

```--show-stacktraces --report-csv-to=/results --report-graphite-to=graphite-service:9109 /config/workload.yaml target scenarioname=target```

**What was Expected**

No startup failure.

**Additional context**

OS: Linux
environment: k8s (GKE)
version info: 4.15.33

**Stacktrace**

```
2740 ERROR [main] ScenarioErrorHandler internal error: unrecognized option:target
java.security.InvalidParameterException: unrecognized option:target
	at io.nosqlbench.engine.cli.NBCLICommandParser.parse(NBCLICommandParser.java:67)
	at io.nosqlbench.engine.cli.NBCLIOptions.parseAllOptions(NBCLIOptions.java:545)
	at io.nosqlbench.engine.cli.NBCLIOptions.<init>(NBCLIOptions.java:191)
	at io.nosqlbench.engine.cli.NBCLIOptions.<init>(NBCLIOptions.java:182)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:175)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:69)
unrecognized option:target
```

**Comment by jshook** [comment]
I've reproduced this. The higher-priority script mode is allowing ".yaml" as a script name, but it should not. This is a side-effect of other recent bug fixes not forcing extensions to match. I'll get a bug fix in for this.

**Comment by jshook** [comment]
The fix is based on a subtle refinement to the NBIO usage semantics, which should be documented separately.

Specifically, any time you pass extensions to NBIO, the returned resource or resources are required to match one of the specified extension, thus the search paths used internally are now modified to reflect this.

**Comment by jshook** [comment]
This should be fixed in latest.
