### ISSUE TITLE
Docker metrics support is currently broken

### ISSUE THREAD

**Issue by Miles-Garnsey** [nosqlbench/nosqlbench#327]
**Describe the bug**

When using the `--docker-metrics` flag, we see a bunch of errors. Firstly, there is an error of the form
```
4858 ERROR [main] DockerHelper Image prom/graphite-exporter not found, unable to automatically pull image. Check docker images
```

This can be resolved by manually downloading the requisite images and re-tagging without the `docker.io/` component at the front of the image name.

Running again yields another error:

```
3881 ERROR [main] ERRORHANDLER {"message":"Cannot link to a non running container: /prom AS /grafana/prom"}

   3881 ERROR [main] ERRORHANDLER for the full stack trace, run with --show-stacktraces
```

Still looking for a workaround on that.

**Additional context**
RHEL 7, nb version 4.15.47.

**Comment by Miles-Garnsey** [comment]
So it looks like this was just because I was using RHEL 7, which has a fairly old kernel and doesn't support docker very well. Closing.

**Comment by jshook** [comment]
Thanks for the follow-up. Maybe we can find a way to make this fail-fast with a helpful message.
