### ISSUE TITLE
ThreadNum() function picks the thread index from the workload alias if the alias contains a digit

### ISSUE THREAD

**Issue by lhotari** [nosqlbench/nosqlbench#384]
**Describe the bug**
ThreadNum() function picks the thread index from the workload alias if the alias contains a digit

**To Reproduce**
1. Start a workload with `alias=somename2` and multiple threads `threads=10`
2. In the workload, the value will be 2 for all threads that use `ThreadNum()` function

**What was Expected**
The ThreadNum() function should return the actual thread index and not parse the index from the workload name (alias) that is included in the thread name.

**Possible solution**
In the current solution, [a regex pattern of `Pattern.compile("^.*?(\\d+).*$")` is used](https://github.com/nosqlbench/nosqlbench/blob/f8d99c086a97c25364a8a6bf23acc3b965fbee6a/virtdata-lib-basics/src/main/java/io/nosqlbench/virtdata/library/basics/shared/nondeterministic/to_int/ThreadNum.java#L39). This regex could be adjusted to pick the last digits instead of the first digits.

**Comment by jshook** [comment]
Fix coming up in next release: A type-safe interface is used to get the value directly.
