### ISSUE TITLE
More guidance on time units in HDR histogram output

### ISSUE THREAD

**Issue by hemidactylus** [nosqlbench/nosqlbench#400]
**What is the ideal scenario for using this feature?**

When producing HDR output with NoSQLBench (`--log-histograms`), the time units used in the resulting HDR file are somewhat heterogeneous.
This may confuse users who most likely want to treat the HDR logfile as a starting point for further custom analyses.

It would be great if the time units were explicitly spelled out, e.g., in the header of the file itself (the first lines consisting of comments).

**Is your feature request related to a problem? Please describe.**

It may be not trivial, for a `nb` user, to work out and reconcile the time units used in various parts of the HDR histograms that are produced.

The first lines of an HDR file look like:
```#logging histograms for session scenario_20211224_144348_474
#[Histogram log format version 1.3]
#[StartTime: 1640353430.819 (seconds since epoch), Fri Dec 24 14:43:50 CET 2021]
"StartTimestamp","Interval_Length","Interval_Max","Interval_Compressed_Histogram"
Tag=cqlkeyvalue_default_schema.cycles.servicetime,1.857,3.147,22.381,HIST[...]
[...]
```

And as far as my investigations and cross-checks went, it seems that:

* the `StartTimestamp` is the number of _seconds_ to add to the "StartTime" mentioned earlier
* the `Interval_Length` is in _seconds_ (and _roughly_ matches the time-window width directive passed to `nb` in the `--log-histograms` parameter)
* the `Interval_Max` is in _milliseconds_ (and modulo unit conversion, matches what is stored in the HDR-encoded compressed-histogram string itself)
* the values themselves being stored in the histogram's buckets are in _nanoseconds_

Adding a comment line at the beginning of each HDR file summarizing the time units employed would sure help users who want to extract plots and further metrics from these HDR logs.

Alternatively, but I can imagine the backward-compatibility issues this might spawn, switching to the same time units everywhere might also help straighten everything out (presumably nanoseconds at that point, since it is convenient - perhaps mandatory - to store integers as "values" in the HDR).

**Would you like to help implementing or testing it?**

I might give it a try, as this could possibly be a very localised change in the HDR file header creation.

**Additional context**

n/a

**Comment by dave2wave** [comment]
PR #578 should have closed this.
