### ISSUE TITLE
either import all the necessary classes for the fluent API or propose to import in the scenario (if it's not a syntax issue)

### ISSUE THREAD

**Issue by pydebrito** [nosqlbench/nosqlbench#407]
Some queries have subtraversals: steps started inside a parenthesis.
Currently these queries fail in fluent API, but work fine in studio and in NB using string API. This might be a missing import at NB level, or something else (particular syntax?)

Examples:

g.V().hasLabel('entity')
           .has('payload', Search.token('mytoken'))
           .out('is_parent_of')
           .has('children_ordinal',within(1,4,7,9))
           .groupCount().by('level')
fails on Search.token.  has('payload', token('mytoken')) has been tried as well without success

g.V().hasLabel('entity')
           .has('id', 0)
           .emit()
           .repeat(out('is_parent_of'))
           .times(2)
           .values('level')
           .sum()
fails on "out"

If this is not a syntax issue, and is indeed an import issue, I would bend towards import the necessary classes if it is possible, to make the life of scenario developers easier, but this could be impractical (?) in which case we would need to be able to import classes in the scenario

Pierre-Yves

**Comment by jshook** [comment]
The fluent op template now supports an `imports` field which is a list of imports which to be added to each script context.
It is in testing now.

**Comment by pydebrito** [comment]
This works now, we can close the issue:
  mainfluent:
    tags:
      phase: mainfluent
    statements:
      main-add:
        type: fluent
        diag: "{diag_ten_pct}"
        graphname: <<graphname:tree>>
        imports:
          - "org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.__"
        fluent: >-
          g.V()
           .hasLabel('entity')
           .has('id', {id})
           .emit()
           .repeat(__.out('is_parent_of'))//out is not recognized
           .times(2)
           .values('level')
           .sum()
