### ISSUE TITLE
Problem with binding when variable is in a solr query.

### ISSUE THREAD

**Issue by jclu123** [nosqlbench/nosqlbench#410]
**Describe the bug**
ATOS team (a DataStax partner) is working on a _redacted_ project that makes heavy use of Solr due to a need for string pattern matching.  They want to load test ther Solr config using NB, and ran into a binding problem when using solr; the schema __**cql-iot-basic-schema**__ used here is attached..  In short the 

solr_query = '{"q":"idx_col3:{type}"}'

causes an error.  But if {type} were substituted with an actual string, then it works.  

However, if the driver were set to "stdout" (i.e. not writing to DSE at all), then {type} binding causes no problems and the entire scenario runs correctly without error.

**To Reproduce**
1. create a DSE 5.1.25 cluster with Search enabled where a node contains an som
2. Create both the schema and populate the table as indicated in **cql_iot_basic-schema.yaml**
3. Run the following nb command:

> nb run driver=cql workload=cql-iot-basic-schema  host=anIpOfDseNode tags=phase:main cycles=1000 port=9042 -v

You will get an error about binding (see toward the bottom of this post).  Then run

> nb run driver=stdout workload=cql-iot-basic-schema  host=anIpOfDseNode tags=phase:main cycles=1000 port=9042 -v

You will not get an error and the output looks correct.

**What was Expected**
I should see solr_query successfully invoked against the DSE cluster and NB run successfully (as in the driver=stdout case).

**Additional context**
NB runs in Linux, DSE is v5.1.25. nb version is 3.12.106, although this problem also happens upto 4.15.64.

[cql-iot-basic-schema.yaml.txt](https://github.com/nosqlbench/nosqlbench/files/7900033/cql-iot-basic-schema.yaml.txt)

**Error of the binding looks like this**
`
2022-01-18 19:48:08,219 INFO [scenarios:001] i.n.e.c.ActivityExecutor [ActivityExecutor.java:169] Stopping executor for cql-iot-basic-schema when work completes.
2022-01-18 19:48:08,223 ERROR [cql-iot-basic-schema:001] i.n.e.a.a.m.CoreMotor [CoreMotor.java:465] Error in core motor loop:java.lang.RuntimeException: Binding error:BindingsTemplate:'type'=>"WeightedStrings('AU:.5;FXK:.25;ECOM:.5');ToString();"=>[AU](String)
java.lang.RuntimeException: Binding error:BindingsTemplate:'type'=>"WeightedStrings('AU:.5;FXK:.25;ECOM:.5');ToString();"=>[AU](String)
        at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:41)
        at io.nosqlbench.activitytype.cql.statements.core.ReadyCQLStatement.bind(ReadyCQLStatement.java:47)
        at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:91)
        at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:72)
`

**Comment by jshook** [comment]
@jclu123 This has to be bound at the parameter level in the query. Since the statement is prepared by default, the binding points (places like `{type}`) have to be assigned wholly to the solr_query field, such as `solr_query = {solr_query_binding}`, where the syntax for the SOLR query is built up in the binding using something like `Template(...)`.

**Comment by jshook** [comment]
I'll close this for now. Please reach out to me again for direct support on this if needed.

**Comment by jclu123** [comment]
Thanks @jshook I will give that solr_query = {solr_query_binding} another go today.  I tried that yesterday as well, based on a past slack post from Matt Overstreet but was still having issues.  Just to be sure, "prepared" has always been set to false in my testing and from the ATOS team.

Thanks again.

**Comment by jshook** [comment]
There may be a different type of formatting requirement for the `prepared: false` case for SOLR. Particularly, we need to make sure that the request is escaped properly within the statement. Please try the above with the default `prepared: true` to get started as we know this case will work. We can start from there to verify the other case too.

**Comment by Meeraa-Lakshmanan** [comment]
Hi @jshook and @jclu123,

I am from ATOS Team,
We tried these below combination for solr_query = {solr_query_binding} as,

**Option 1:**

type: WeightedStrings('AU:.5;FXK:.25;ECOM:.5';ToString();
solr_query_result : Template('{"q":"idx_col3:{type}"}');
 
 select * from  table  where  solr_query ={solr_query_result};

**Output for Option 1 (driver=stdout):** 
 select * from table where  solr_query = {"q":"idx_col3:{type}"};  
   Cannot able to see the actual value in place of {type}

**Option 2:**

solr_query_result : Template('{"q":"idx_col3:WeightedStrings('AU:.5;FXK:.25;ECOM:.5')"}');

select * from  table where solr_query ={solr_query_result};

**Output for Option 2 (driver=stdout):** 
   Getting below error while trying with direct binding

line 1:44 token recognition error at: ':'
line 1:45 token recognition error at: '.'
line 1:42 mismatched input 'AU' expecting {',', ')'}
line 1:51 token recognition error at: ':'
line 1:52 token recognition error at: '.'
line 1:60 token recognition error at: ':'
line 1:61 token recognition error at: '.'
line 1:53 no viable alternative at input 'FXK25'
line 1:62 no viable alternative at input 'ECOM5'
[AU, 5, FXK, 25, ECOM, 5, ')"}', )]
13:00:38.140 [scenarios:001] WARN  i.n.engine.core.script.Scenario - Error in scenario, shutting down.
13:00:38.206 [main] ERROR i.n.engine.core.ScenarioErrorHandler - java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'cql-iot-basic-schema':
java.lang.RuntimeException: Error parsing input 'Template('{"q":"idx_col3:WeightedStrings('AU:.5;FXK:.25;ECOM:.5')"}');'
13:00:38.207 [main] ERROR i.n.engine.core.ScenarioErrorHandler - for the full stack trace, run with --show-stacktraces
java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'cql-iot-basic-schema':
java.lang.RuntimeException: Error parsing input 'Template('{"q":"idx_col3:WeightedStrings('AU:.5;FXK:.25;ECOM:.5')"}');'

We tried prepared:false/true  both options.

Could you please help us to resolve this issue.

**Comment by msmygit** [comment]
@Meeraa-Lakshmanan, @jclu123 

All I had to do was to set the bindings as following:
```
solr_query_result: Template('{"q":"idx_col3:{}"}', WeightedStrings('AU:.5;FXK:.25;ECOM:.5'));
```

With the above _binding_, either if we have `prepared: true` or `prepared: false` it works like a charm for the below query,

```
select * from <<ks:cds_l1_etnms_ks>>.sample_testing_performance where solr_query = {solr_query_result};
```

I hope that helps!

**Comment by msmygit** [comment]
FWIW, I did the above using:
```
% nb --version
4.15.48
```

**Comment by jclu123** [comment]
@msmygit your suggestion works, thank you very much (although that is some next level nb-binding incantation you conjured up there).  @Meeraa-Lakshmanan, please follow what Madhavan suggested.

**Comment by Meeraa-Lakshmanan** [comment]
@msmygit,@jclu123 

Thank you so much,Its working.
