### ISSUE TITLE
convert Pulsar driver from ActivityType to DriverAdapter

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#438]

**Comment by eolivelli** [comment]
We could find someone in the Streaming team for this task

Let me ask

**Comment by MMirelli** [comment]
I can probably help with this. @jshook do you have any deadline / timeline for this refactoring to be in place?

**Comment by jshook** [comment]
@MMirelli Sorry for the late reply.

There is no deadline. However, there are people waiting for nb5 availability in user environments, and this is part of the nb5 release plan. So, sooner is better. I'm happy to work together on this as well to accelerate the migration.

**Comment by jshook** [comment]
Completed
