### ISSUE TITLE
Verify license boilerplate on all files with CI/CD

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#449]
All of the project files must be verified as having the APLv2 license boilerplate on each file. This should be done automatically with pre-commit hooks or something similar. It must be automatic at least for stable release, but more ideally for every commit and PR.

**Comment by eolivelli** [comment]
Please don't go with precommit hooks.
I believe that adding apache rat maven plugin in the pom is enough. You can activate it in the verify phase for instance

**Comment by jshook** [comment]
Thanks for the pointer, I'll do that instead!

**Comment by jshook** [comment]
The main branch now has the apache rat maven plugin running on all modules for all Java source files.
The build will fail if it is attempted with a missing license header.
Generated directories are excluded, as these are derivatives of other licensed content.
