### ISSUE TITLE
Diagnostics: provide a way to see templated variables applied before YAML parsing

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#453]
When non-trivial template variable values are used, such as those with quotes, it can be difficult to know whether the values are applied with correct YAML or other language syntax. It would be very helpful for users to be able to see the results of template variable interpolation as a diagnostic step.

**Comment by dave2wave** [comment]
We can implement an NBAdvisorPoint in the YAML processing which shows the yaml post interpolation.
