### ISSUE TITLE
All metrics reporting methods should allow for uniform sampling settings

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#478]
These settings should be uniformly configurable for all metrics reporting channels, so that when users compare data between them, they know that the data is being captured and reduced in the same way.
* HDR digits
* sampling interval
* reservoir type

**Comment by jshook** [comment]
This is to enable empirical cross-checking between the various metrics output formats. This should not be considered complete unless/until unit tests are added which provides numerical verification for all metrics channels.

**Comment by dave2wave** [comment]
Superseded by OpenMetrics integration
