### ISSUE TITLE
Static guidebook via docs discovery

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#50]
We now have a static guidebook on the way (Thanks @phact!).

The next phase of improvement on this should be to eliminate local scripting needed to find and assemble the content for the static view. Specifically, if we can delegate the markdown content discovery to a docsfinder command or something similar, we should.

The end goal is for an activity type contributor to be able to add docs in java using the extant mechanisms, and have that appear both the dynamic and the static guidebook forms without further integration or scripting work.

**Comment by phact** [comment]
This is done right?

**Comment by jshook** [comment]
This is complete. Some refinements are needed to ease builds and merges, but these can be handled in a separate issue.
