### ISSUE TITLE
expose JVM options in the wrapper script when building appimage binary

### ISSUE THREAD

**Issue by weideng1** [nosqlbench/nosqlbench#51]
We will need to be able to specify GC related parameters and heap settings.

**Comment by jshook** [comment]
This should be complete in master.
The way to override JVM settings with the nb binary is to set an env var for JAVA_OPTS.
For example, with bash, you can do this:
`JAVA_OPTS=-Xmx2048m ./nb`
or
```
export JAVA_OPTS=-Xmx2048m
./nb
```
