### ISSUE TITLE
Template Variables: Allow for intermediate value expansion in named scenarios

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#542]
Template variables and named scenarios are both forms of partial rendering based on a template. How they interact is not clearly defined, although previously they were allowed to layer in a useful way. Specifically, template parameters within the named scenario commands were resolved such that the value could provide a simple override.

For example,

    scenarios:
      default:
        command param1===TEMPLATE(testparam1,defvalue)

... would allow a user to provide an alternate value for `param1` by setting the template variable `testparam1`, but not by directly setting `param`. This is a useful pattern for some scenarios, and has been used by convention in multiple places.

This should be codified, documented, and tested as such. It appears that the behavior is not working as previously on recent nb5 releases.

**Comment by dave2wave** [comment]
This is functioning correctly.
```
    1080 TRACE [main] OpsLoader    Applying string transformer to data:bindings:
  map_sized: MapSized(1, NumberNameToString(), NumberNameToString(), NumberNameToString(), NumberNameToString())
  map<text,text>: MapSized(3, Combinations('A-Z;0-9'), NumberNameToString(), NumberNameToString());
scenarios:
  default:
    command param1===TEMPLATE(testparam1,defvalue)

    1085 TRACE [main] StrInterpolator Template parameter 'testparam1' applied as 'defvalue'
    1086 INFO  [main] OpsLoader    workload URI: 'file:///Users/dave.fisher/map_sized.yaml'
    1088 TRACE [main] RawOpsLoader Applying string transformer to yaml data:bindings:
  map_sized: MapSized(1, NumberNameToString(), NumberNameToString(), NumberNameToString(), NumberNameToString())
  map<text,text>: MapSized(3, Combinations('A-Z;0-9'), NumberNameToString(), NumberNameToString());
scenarios:
  default:
    command param1===defvalue

    1095 TRACE [main] StrInterpolator removed template params after applying:{testparam1=defvalue}
```
