### ISSUE TITLE
Scenario alias expansion has a format regression

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#544]
On a recent test, the alias names which are auto-generated by named scenario parsing contained the "file path" base name instead of the logically reduced and consistent name as documented for named scenarios. (This was on 4.17 / main)
This is likely due to a related change in workload path resolution, where the simpler name was carried into the alias compositing afterwards. This should be fixed to restore consistent behavior for integrated metrics naming.

**Comment by dave2wave** [comment]
Phrasing is too ambiguous, needs info, and no longer relevant
