### ISSUE TITLE
histostats logger may have an accuracy regression

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#560]
@hemidactylus reports that the histostats percentile sample points are off by 2 orders of magnitude. This was likely due to an incompatiblity between histogram reservoir implementations as these vary between dropwizard and HDR implementation historically.

**Comment by hemidactylus** [comment]
I'll do a PR to fix it in a couple of days or so.

**Comment by hemidactylus** [comment]
I believe this can now be marked as closed. (after PR #563 ).
