### ISSUE TITLE
Warn user if they use "count" for the v4.17+ error handler parameters

### ISSUE THREAD

**Issue by hemidactylus** [nosqlbench/nosqlbench#561]
The parameter `errors=count` has become `errors=counter` starting with v4.17 onward.

While the translation happens automatically, it would be good to issue a warning (perhaps linking to the docs page) to help users transition to the new error handler usage.

(possibly related to other automatic conversion of error-handler parameters, if any occur).

**Comment by jshook** [comment]
merged in main
