### ISSUE TITLE
Java/JDK minimum version in "BUILDING.md" should be 17 not 12

### ISSUE THREAD

**Issue by tatu-at-datastax** [nosqlbench/nosqlbench#584]
Looking at `BUILDING.md`, minimum Java version is said to be 12. But trying to do Maven build I get exception indicating that the actual baseline is 17.

**Comment by tatu-at-datastax** [comment]
Ok actually I think this varies by branch. Not quite sure what the role of `main` is at this point, so this issue may or may not make sense. If not, feel free to close along with PR.

**Comment by dave2wave** [comment]
Version needed is now Java 21 and `BUILDING.md` is now updated
