### ISSUE TITLE
CpuInfo class is too Linux dependent

### ISSUE THREAD

**Issue by alexott** [nosqlbench/nosqlbench#61]
Right now, `CpuInfo` and `CpuInfo.ProcDetails` classes are too Linux dependent as they are reading `/proc/cpuinfo`, and other files from `/proc/` that aren't available on the Mac OS, and other platforms...  We need to decrease dependency on the low level stuff like this, by maybe using https://github.com/oshi/oshi, or something like...

**Comment by jshook** [comment]
As long as oshi doesn't re-introduce a guava dependency, and it is reasonably small in packaged form, I'm ok with adding a dependency on it.
