### ISSUE TITLE
Reconsider parameter names for yaml and type

### ISSUE THREAD

**Issue by phact** [nosqlbench/nosqlbench#63]
When using a built in workload, `yaml` is rather meaningless and when using a custom  `yaml` it is still rather vague. Aaron proposes we use the parameter `workload` instead. We could also use `activity-definition` if we wanted to match the language in the source code but I think `workload` is more intuitive for a new user.

`type` is a bit harder because nosqlbench supports things like stdout, tcpclient, kafka, etc. that do not fit into a more specific description like  `database` or `driver`. We could use the term `activity` or `activity-type` to match what we call things in the source code but again, not sure how intuitive those are for new users. Open to suggestions on a better term for `type`.  

Regardless, we would continue to support the old parameter names for backwards compatibility.

**Comment by michaelsembwever** [comment]
It would be great if the new user experience was…

It's as simple as
```./nb run```

If you want to do something more than a key-value workload, like time-series, it's just
```./nb run workload=baselines/time-series```

If you want to load nodes that are remote, it's just
```./nb run hosts=…`

If you want to generate load from a different driver, it's just
```./nb run driver=kafka```

--
A lot of new users get on board via a tactile learning approach. This gives it to them.
Not to mention, half the time Cassandra dev/ops use stress it's nothing more than putting anything through a node to generate some activity, needing nothing more than the `./nb run` invocation. Going down this route, then the new names of the parameters as used above (IMHO) land better.

**Comment by phact** [comment]
@michaelsembwever we're doing some related improvements in another issue that I think you'll like-
https://github.com/nosqlbench/nosqlbench/issues/67.

This particular issue is around considering adding synonyms for the current terms `yaml` and `type`.

I don't particularly love `driver` but it may be the best we can do. @jshook thoughts?

**Comment by jshook** [comment]
The word driver by itself can lead to confusion, because there is a whole layer of additional functionality that we add for testing purposes on top of the native driver.
We might consider other alternatives like "adapter" or "protocol" without overloading the term driver too much.

**Comment by phact** [comment]
Addressed here https://github.com/nosqlbench/nosqlbench/compare/issue-87?expand=1

**Comment by jshook** [comment]
This has been addressed. We're doing minor refinements on the named scenarios support to make it better.
