### ISSUE TITLE
Add nb binary artifacts to CI release actions

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#70]
The release is fully automated presently except for the addition of the nb binary to the releases.
Because the release is automated by maven without exposing the github release details to github actions, we'll need to capture the release version so that the binary upload can find it by tag name.
This can be done within the job by using the environment vars already provided, or a descriptor can be uploaded to the actions artifacts.

**Comment by phact** [comment]
done?

**Comment by jshook** [comment]
done
