### ISSUE TITLE
[cqld4 driver] JSON driver config not being applied

### ISSUE THREAD

**Issue by anthonydugois** [nosqlbench/nosqlbench#736]
When specifying a JSON file in `driverconfig` activity parameter of cqld4 driver (as described in https://github.com/nosqlbench/nosqlbench/blob/main/adapter-cqld4/src/main/resources/cqld4.md), options defined in the file are not applied during the experiment.

**To Reproduce**
Start a Cassandra cluster and try the following JSON file as driver config:

```json
{
  "advanced.metadata.token-map.enabled": false
}
```

Then create a keyspace with replication factor of 1 and a simple table. Insert data and execute some SELECT requests randomly. Requests are still always routed on their primary replica.

Specifying the option as an activity parameter (`driver.advanced.metadata.token-map.enabled`) does not work either.

**What was Expected**
Requests should not be systematically routed on their primary replica anymore as driver token-awareness has been disabled.

**Additional context**
```
> ./nb --version
4.17.27
```

**Workaround**
Using a `.conf` file instead of a `.json` file seems to work:
```
datastax-java-driver {
  advanced.metadata.token-map.enabled = false
}
```

**Comment by jshook** [comment]
This looks like a feature request or a docs clarification issue. We'll take this as a request to support both extensions.

**Comment by jeffbanks** [comment]
@anthonydugois thank you for reporting this issue.  

We will be discussing how to improve our docs to better illustrate `driver` and `nosqlbench` alignment.

Is it possible for you to upgrade to `nb5`? This version has better support for the `cqld4` driver. 

If not, it looks as if the `.conf` is a viable workaround.

We will still be researching the root cause with `v4.17.27`, as that should be working based on the configuration you provided.

**Comment by anthonydugois** [comment]
@jeffbanks I did use `nb5`, sorry for the typo. Actually I tested this with the official Docker image, which uses `nb5.jar` as entrypoint:

```
> docker run nosqlbench/nosqlbench:nb5preview --version
4.17.27
```

I confirm that `.conf` files are working as expected.

**Comment by dave2wave** [comment]
We are currently using driverconfig.json so this must be working now.
