### ISSUE TITLE
Implement remaining drivers on nb5 API

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#782]
One of the key promises of NoSQLBench is that of re-usable concepts and workflows. This means that time invested by users to learn more advanced usage patterns will be rewarded with an understanding of how to apply that knowledge elsewhere. The driver interfaces and capabilities are a key focal point for this. In other words, when the drivers support a uniform set of integrations and behaviors, the toolkit becomes simpler and more powerful at the same time.

## Challenge

Previously, driver developers had to effectively copy and emulate the behavior which was established by convention, using code which was not managed by the core runtime. As well, the concepts and tooling needed to streamline the process of converting templates to operations was lacking in terms of clarity and supportive APIs.

## Remedy

2. [x] #431
5. [x] #434
6. [x] #435
7. [x] #436
9. [x] #438

**Comment by dave2wave** [comment]
I suspect that this and the four remaining tasks are complete
