### ISSUE TITLE
Build guidebook strictly as as a secondary artifact

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#82]
Presently, the guidebook application builds into the source tree as resource content.
This complicates commits after builds. We should try to move this content into an ephemeral artifact location like "target".

We can .gitignore the dev view and staging versions in the source tree, and stage the generated app in docsys/target/guidebook.

**Comment by phact** [comment]
done?

**Comment by jshook** [comment]
done for this phase. Additional work is needed to make the builder simpler, but that can be addressed separately.
