### ISSUE TITLE
Add LRU expiry and maximum limit option for space cache.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#860]
When using the `space` feature for advanced driver testing, it is easy for users to over subscribe threads.

A set of cache-control options for an adapter's space cache should be provided which allow the user to do any or all of these:

- configure an optional LRU cache size limit which causes caches to be dropped. `spaces_lrusize`
- configure an optional cache size limit which causes an error to be thrown. `spaces_limit`
- make these two options mutually exclusive.

**Comment by dave2wave** [comment]
Superseded by new space design
