### ISSUE TITLE
Add `script` and `scenario` keywords to nbcli for expicit use

### ISSUE THREAD

**Issue by phact** [nosqlbench/nosqlbench#87]
Right now if you say `./nb name` nb will match scripts first, then yamls.

I propose we keep this functionality to grease the first time UX wheels but we also want to provide explicit keywords:

`./nb script name` will only match scripts

`./nb scenario name` will only match yamls

**Comment by phact** [comment]
Also, the default help on the cli needs to reflect this.

**Comment by jshook** [comment]
We need to make sure that `./nb scenario name` only matches for yamls with named scenarios. This just means adding useful error messages, but it's worth adding a test for that.

**Comment by phact** [comment]
As part of the docs changes, we're making topics.md modular. Everything except the quick start docs will go in a topic. The topics are module (activity type specific) and get merged at build time.

**Comment by jshook** [comment]
done?

**Comment by jshook** [comment]
Closing this. I think it is done. We can open more if needed for anything we missed here.
