### ISSUE TITLE
Clean up error handling semantics in ActivityExecutor

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#879]
@jeffbanks  pointed out that there are some unclear patterns of exception signaling in ActivityExecutor. The semantics and methods for handling potentially multiple concurrent errors in an activity should be made clear. Any ambiguity about how concurrent errors are handle should be avoided. Some small changes can probably address this.

**Comment by jeffbanks** [comment]
@jshook unless there are some other exception handling additions we want to include, I believe #880  covered this one pretty well as we move forward with nb5.  wdyt?

**Comment by jshook** [comment]
agreed
