### ISSUE TITLE
refinements to --list-workloads

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#92]
If a user types `nb --list-workloads <path>`, then they should get a list of workloads contained in the path. If the path is a found directory, it should include all workloads within the directory. If the path is a workload file, then it should only include that workload's scenarios in its output.

We may also want to square up the terms between workloads and named scenarios.
Presently, when a user types --list-workloads, they see a list of workloads and scenarios, when they are really interested in the scenarios.

Is there a good case to have --list-workloads and --list-scenarios?

**Comment by phact** [comment]
Actually, today --list-workloads only shows workloads that have scenarios.

**Comment by jshook** [comment]
Yes, but isn't the intent by the user in this case to see the scenarios in the workloads specifically?

**Comment by jshook** [comment]
I've added a --list-scenarios that takes on the responsibility above, and refined the output to be easier to read. Additionally, --list-workloads now just gives a simple list.
