### ISSUE TITLE
NoSQLBench 4 syntax fails with NoSQLBench 5: "There were no active statements with tag filter 'phase:[phasename]', since all 8 were filtered out."

### ISSUE THREAD

**Issue by dmorse76** [nosqlbench/nosqlbench#952]
(First of all, my apologies, today is the first day I've tried upgrading from NoSQLBench 4 to 5, so this may be a simple syntax error)

**Describe the bug**
Commands that used to work on NoSQLBench 4.15 now fail on NoSQLBench 5.17.1-release with the error message " There were no active statements with tag filter 'phase:schema|ramup|main', since all 8 were filtered out."

**To Reproduce**
1. Run any of these commands (which worked on nb 4.15):
```
./nb5 -v run driver=cql workload=cql-keyvalue2 tags=phase:schema host=nosqlbencha
./nb5 -v run driver=cql workload=cql-keyvalue2 tags=phase:rampup host=nosqlbencha cycles=300m threads=128 --progress console:10s
./nb5 -v start alias=NoSQLBenchA0 driver=cql workload=cql-keyvalue2 host=NoSQLBenchA0 cycles=200m threads=36  --progress console:10s waitmillis 60000 stop NoSQLBenchA0
```

**What was Expected**
NoSQLBench to run the selected phase.

**Additional context**
OS: Ubuntu 22.04.1 LTS

Environment: VM
Version info: 5.17.1-release

**Console commands and errors**
[nb5-errors.txt](https://github.com/nosqlbench/nosqlbench/files/10512907/nb5-errors.txt)

**Comment by jshook** [comment]
Thanks for the report David. Some sanity checking logic and parameter name deprecations needed to be patched up.
This may have the changes you need: https://github.com/nosqlbench/nosqlbench/releases/tag/5.17.1-preview
(This will be rolled into a proper release soon)

**Comment by dmorse76** [comment]
Hi Jonathan, sorry for the delay.  You're right, I just had to update the syntax a bit, i.e. `tags=phase:schema` and `tags=phase:rampup` are now `tags=block:schema` and `tags=block:rampup`.
Thanks for the help!
