### ISSUE TITLE
refinement to named scenarios parameter handling

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#96]
For the new named scenarios parameter handling, there are a few details we need to clarify and finish so that it is maximally useful.

## parameter overrides
Currently, when you specify parameters on the command line, such as with 
```
./nb cql-iot host=foo threads=auto
```
... There is no control over which parts of which scenario commands have overrides.
This is problematic, in that you *do* want more threads for main or rampup phase, but you *do not* want more than 1 thread for schema.

I have a simple solution for this, in terms of how we express which parameters *may* be overridden and which may not:

Within each line of a named scenario, we can use an assignment operator for the parameters which should not be modified by users. If we use the equals-assignment operator like `:=`, then it makes it easy to follow the normal form. Assigning a parameter on the command line for one of these parameters is a silent failure. That is, it is not an error for an assignment to be provided for which there is a silent default assigned with `:=`.

As well, it can be possible to assign parameters which are verbotten in the scenario command. If an scenario command contains a parameter with an assignment like `==`, then this is a strong declaration that the value should not be overridden, and further, assignment to it in any case is a reason to warn the user that this is not accepted for this named scenario. The reason for this, can be seen below in the example. If a user assigns a value to `cycles=` in their command line, then they will be mislead about what is actually happening. It should be made clear that assigning to `rampup-cycles` and `main-cycles` is appropriate, but that assigning to `cycles` is not, given that the values of these parameters need to be contextualized per-step.

For example:
```
scenarios:
  default:
    - run type=cql tags:=phase:schema threads:=1 cycles:=1
    - run type=cql tags:=phase:rampup cycles==TEMPLATE(rampup-cycles,10000000)
    - run type=cql tags:=phase:main cycles==TEMPLATE(main-cycles,10000000)
```
In this form, it is still clear that `rampup-cycles` and `main-cycles` are special types of parameters. 
Further, it shows that you cannot set cycles directly.

The previous 'yaml=' and 'hosts=' parameters are no longer needed here. The yaml= support is already in master, and users can set hosts= if the defaults do not suffice.

It also means that users will be able to override threads for the 2nd and 3rd command while ensuring that schema updates complete successfully and in linearized order as specified.

**Comment by phact** [comment]
At first I didn't like the idea of adding a new operator but now I realize it's a clever way of shifting some complexity and confusion from the scenario user to the more advanced scenario designer so I'm +1.

**Comment by jshook** [comment]
This is documented under the scenario building docs section 'Named Scenarios'
