### ISSUE TITLE
"mvn clean install" sometime fails `nbr` module unit tests intermittently

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#962]
**Describe the bug**
`mvn clean install` fails unit tests. See attached file where I've tried to capture running `mvn clean install --debug` output. FWIW, when we run `mvn clean package [-DskipTests]`, it runs without any issues. This is only intermittent.

**To Reproduce**
1. git clone from `main` branch.
2. try and execute `mvn clean install`.
3. See the error in the attached file.

**What was Expected**
`mvn clean install` command when executed passes.

**Additional context**
OS: macOS Monterey 12.6.3
environment: OpenJDK 17.0.2
version info (`./nb --version` or `java -jar nb.jar --version`): `15.17.1-SNAPSHOT`

**Screenshots, if applicable**
[nb-15-17-1-SNAPSHOT-mvn-clean-install-fail_20230127.txt](https://github.com/nosqlbench/nosqlbench/files/10523700/nb-15-17-1-SNAPSHOT-mvn-clean-install-fail_20230127.txt)

**Comment by jshook** [comment]
I believe this has been addressed in latest main. If you see this specific error again, please re-open the issue.
