### ISSUE TITLE
Better error message for tag filtering mismatch

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#984]
When tag filtering filters out all of the op templates in a workload, there are some specific cases which we could detect and provide better feedback on:

- a tag name was specified, but *none* of the op templates have that tag name.
  - This is not an error per se, as it might be a valid scenario for automation
  - It is *likely* an error if it is driven from user behavior.
  - For cases like this, we don't want to interrupt the scenario with an error, but we do want to inform the user.
  - It is possible to use levenschtien distance to match what was intended and provide a prescriptive solution.

- a tag name and literal tag value are specified, the tag name matches, but the tag value does not *and* there are no op templates which could match the tag value.
  - as with the above scenario, this may not always be an error. (Imagine automation over many files which are not in consideration here)
  - As above, we would like to inform the user with a useful error.

This should be handled with the same mechanism as in #12

**Comment by dave2wave** [comment]
We currently are finding an error here. The change requested is fold that message through NBAdvisorOutput.test
