### ISSUE TITLE
Actions thread state model is missing valid transition from stop*->Errored

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#987]
In the case that an activity has a short run, or a low number of cycles *and* there is an error during it's shutdown or cycle execution, it will transition by default to Stopping and then Stopped via normal flow, but the async exception handling logic may not flag an error on the activity early enough.

When there is an error, the final state of the activity should be Errored in any case.
When there isn't an error, the final state should never be Errored. (Should be either Finished or Stopped).

This needs further review, but the first fix to be applied should be to allow Stopping  -> Errored. Both the transition and final states Stopping and Stopped should be allowed to be moved to Errored, because of a potential race. But, a better solution is to make sure that all transitions are atomic and that we account for each transition uniquely.

**Comment by msmygit** [comment]
This was reproduced in `5.17.1-PREVIEW`. Example error stack is below:
```
4697 ERROR [/path/to/workload/somedriver-someoperation.yaml:004] CoreMotor    Error in core motor loop:java.lang.RuntimeException: Invalid transition from Stopping to Errored
java.lang.RuntimeException: Invalid transition from Stopping to Errored
	at io.nosqlbench.engine.api.activityimpl.MotorState.enterState(MotorState.java:66)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:397)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
