### ISSUE TITLE
Clarify docs to specify a cycle interval starting from > 0 

### ISSUE THREAD

**Issue by alicel** [nosqlbench/nosqlbench#99]
There is no example or detail of the syntax to specify a cycle interval starting from a number higher than zero (e.g. cycles=30M..100M)

I would suggest making this clearer, perhaps with an explicit example in the Getting Started section or detailing it in the Cycle explanation in the Core Concept page.

**Comment by alicel** [comment]
It would also be good to mention if cycle is 0- or 1-based.

**Comment by jshook** [comment]
Added an info callout for
```
The cycles parameter is not just a quantity. It is a range of values. The cycles=n format is short for cycles=0..n, which makes cycles a zero-based quantity by default. For example, cycles=5 means that the activity will use cycles 0,1,2,3,4, but not 5. The reason for this is explained in detail in the Activity Parameters section.
```

Also, detailed docs on this parameter are here:
http://docs.nosqlbench.io/#/docs/basics%2Factivity_parameters

I don't think that the navigability is high enough on the doc site yet. Can you review these areas, though to see if the details on cycles are better now?

**Comment by jshook** [comment]
Should I close this issue, @alicel ?

**Comment by alicel** [comment]
Yes, it is much clearer now. It looks good to me, closing the issue now. Thank you!
