### ISSUE TITLE
On nb5 exit, the latest logfile, scriptfile, and summary file should be symlinked

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#998]
A shutdown hook should automatically symlink logs/<latest>.log to the name logs/session.log, unlinking any previous on.
When the scenario script and summary file are written, they should have the same treatment.

**Comment by dave2wave** [comment]
Was this enhancement completed?

**Comment by dave2wave** [comment]
See https://github.com/nosqlbench/nosqlbench/commit/2330661fe2e540e03ea9e32559cac4c9052c552d
